//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 05:15:12 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacpdv.v7_0;
