//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 05:15:12 PM CEST 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacpdv.v7_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Isporuka, sadrži vrijednost i porez
 * 
 * <p>Java class for sIsporuka complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sIsporuka">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Vrijednost" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Porez" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sIsporuka", propOrder = {
    "vrijednost",
    "porez"
})
public class SIsporuka {

    @XmlElement(name = "Vrijednost", required = true)
    protected BigDecimal vrijednost;
    @XmlElement(name = "Porez", required = true)
    protected BigDecimal porez;

    /**
     * Gets the value of the vrijednost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVrijednost() {
        return vrijednost;
    }

    /**
     * Sets the value of the vrijednost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVrijednost(BigDecimal value) {
        this.vrijednost = value;
    }

    /**
     * Gets the value of the porez property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPorez() {
        return porez;
    }

    /**
     * Sets the value of the porez property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPorez(BigDecimal value) {
        this.porez = value;
    }

}
