//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 05:15:12 PM CEST 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacpdv.v7_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tijelo obrasca
 * 
 * <p>Java class for sTijelo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sTijelo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Podatak000" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak100" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak101" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak102" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak103" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak104" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak105" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak106" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak107" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak108" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak109" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak110" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak200" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak201" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak202" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak203" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak204" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak205" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak206" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak207" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak208" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak209" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak210" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak211" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak212" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak213" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak214" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak300" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak301" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak302" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak303" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak304" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak305" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak306" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v7-0}sIsporuka"/>
 *         &lt;element name="Podatak307" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak400" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak500" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak600" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="Podatak700" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;sequence>
 *           &lt;element name="Povrat" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2" minOccurs="0"/>
 *           &lt;element name="Predujam" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2" minOccurs="0"/>
 *           &lt;element name="UstupPovrata" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sTijelo", propOrder = {
    "podatak000",
    "podatak100",
    "podatak101",
    "podatak102",
    "podatak103",
    "podatak104",
    "podatak105",
    "podatak106",
    "podatak107",
    "podatak108",
    "podatak109",
    "podatak110",
    "podatak200",
    "podatak201",
    "podatak202",
    "podatak203",
    "podatak204",
    "podatak205",
    "podatak206",
    "podatak207",
    "podatak208",
    "podatak209",
    "podatak210",
    "podatak211",
    "podatak212",
    "podatak213",
    "podatak214",
    "podatak300",
    "podatak301",
    "podatak302",
    "podatak303",
    "podatak304",
    "podatak305",
    "podatak306",
    "podatak307",
    "podatak400",
    "podatak500",
    "podatak600",
    "podatak700",
    "povrat",
    "predujam",
    "ustupPovrata"
})
public class STijelo {

    @XmlElement(name = "Podatak000", required = true)
    protected BigDecimal podatak000;
    @XmlElement(name = "Podatak100", required = true)
    protected BigDecimal podatak100;
    @XmlElement(name = "Podatak101", required = true)
    protected BigDecimal podatak101;
    @XmlElement(name = "Podatak102", required = true)
    protected BigDecimal podatak102;
    @XmlElement(name = "Podatak103", required = true)
    protected BigDecimal podatak103;
    @XmlElement(name = "Podatak104", required = true)
    protected BigDecimal podatak104;
    @XmlElement(name = "Podatak105", required = true)
    protected BigDecimal podatak105;
    @XmlElement(name = "Podatak106", required = true)
    protected BigDecimal podatak106;
    @XmlElement(name = "Podatak107", required = true)
    protected BigDecimal podatak107;
    @XmlElement(name = "Podatak108", required = true)
    protected BigDecimal podatak108;
    @XmlElement(name = "Podatak109", required = true)
    protected BigDecimal podatak109;
    @XmlElement(name = "Podatak110", required = true)
    protected BigDecimal podatak110;
    @XmlElement(name = "Podatak200", required = true)
    protected SIsporuka podatak200;
    @XmlElement(name = "Podatak201", required = true)
    protected SIsporuka podatak201;
    @XmlElement(name = "Podatak202", required = true)
    protected SIsporuka podatak202;
    @XmlElement(name = "Podatak203", required = true)
    protected SIsporuka podatak203;
    @XmlElement(name = "Podatak204", required = true)
    protected SIsporuka podatak204;
    @XmlElement(name = "Podatak205", required = true)
    protected SIsporuka podatak205;
    @XmlElement(name = "Podatak206", required = true)
    protected SIsporuka podatak206;
    @XmlElement(name = "Podatak207", required = true)
    protected SIsporuka podatak207;
    @XmlElement(name = "Podatak208", required = true)
    protected SIsporuka podatak208;
    @XmlElement(name = "Podatak209", required = true)
    protected SIsporuka podatak209;
    @XmlElement(name = "Podatak210", required = true)
    protected SIsporuka podatak210;
    @XmlElement(name = "Podatak211", required = true)
    protected SIsporuka podatak211;
    @XmlElement(name = "Podatak212", required = true)
    protected SIsporuka podatak212;
    @XmlElement(name = "Podatak213", required = true)
    protected SIsporuka podatak213;
    @XmlElement(name = "Podatak214", required = true)
    protected SIsporuka podatak214;
    @XmlElement(name = "Podatak300", required = true)
    protected SIsporuka podatak300;
    @XmlElement(name = "Podatak301", required = true)
    protected SIsporuka podatak301;
    @XmlElement(name = "Podatak302", required = true)
    protected SIsporuka podatak302;
    @XmlElement(name = "Podatak303", required = true)
    protected SIsporuka podatak303;
    @XmlElement(name = "Podatak304", required = true)
    protected SIsporuka podatak304;
    @XmlElement(name = "Podatak305", required = true)
    protected SIsporuka podatak305;
    @XmlElement(name = "Podatak306", required = true)
    protected SIsporuka podatak306;
    @XmlElement(name = "Podatak307", required = true)
    protected BigDecimal podatak307;
    @XmlElement(name = "Podatak400", required = true)
    protected BigDecimal podatak400;
    @XmlElement(name = "Podatak500", required = true)
    protected BigDecimal podatak500;
    @XmlElement(name = "Podatak600", required = true)
    protected BigDecimal podatak600;
    @XmlElement(name = "Podatak700", required = true)
    protected BigDecimal podatak700;
    @XmlElement(name = "Povrat")
    protected BigDecimal povrat;
    @XmlElement(name = "Predujam")
    protected BigDecimal predujam;
    @XmlElement(name = "UstupPovrata")
    protected BigDecimal ustupPovrata;

    /**
     * Gets the value of the podatak000 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak000() {
        return podatak000;
    }

    /**
     * Sets the value of the podatak000 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak000(BigDecimal value) {
        this.podatak000 = value;
    }

    /**
     * Gets the value of the podatak100 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak100() {
        return podatak100;
    }

    /**
     * Sets the value of the podatak100 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak100(BigDecimal value) {
        this.podatak100 = value;
    }

    /**
     * Gets the value of the podatak101 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak101() {
        return podatak101;
    }

    /**
     * Sets the value of the podatak101 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak101(BigDecimal value) {
        this.podatak101 = value;
    }

    /**
     * Gets the value of the podatak102 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak102() {
        return podatak102;
    }

    /**
     * Sets the value of the podatak102 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak102(BigDecimal value) {
        this.podatak102 = value;
    }

    /**
     * Gets the value of the podatak103 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak103() {
        return podatak103;
    }

    /**
     * Sets the value of the podatak103 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak103(BigDecimal value) {
        this.podatak103 = value;
    }

    /**
     * Gets the value of the podatak104 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak104() {
        return podatak104;
    }

    /**
     * Sets the value of the podatak104 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak104(BigDecimal value) {
        this.podatak104 = value;
    }

    /**
     * Gets the value of the podatak105 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak105() {
        return podatak105;
    }

    /**
     * Sets the value of the podatak105 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak105(BigDecimal value) {
        this.podatak105 = value;
    }

    /**
     * Gets the value of the podatak106 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak106() {
        return podatak106;
    }

    /**
     * Sets the value of the podatak106 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak106(BigDecimal value) {
        this.podatak106 = value;
    }

    /**
     * Gets the value of the podatak107 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak107() {
        return podatak107;
    }

    /**
     * Sets the value of the podatak107 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak107(BigDecimal value) {
        this.podatak107 = value;
    }

    /**
     * Gets the value of the podatak108 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak108() {
        return podatak108;
    }

    /**
     * Sets the value of the podatak108 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak108(BigDecimal value) {
        this.podatak108 = value;
    }

    /**
     * Gets the value of the podatak109 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak109() {
        return podatak109;
    }

    /**
     * Sets the value of the podatak109 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak109(BigDecimal value) {
        this.podatak109 = value;
    }

    /**
     * Gets the value of the podatak110 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak110() {
        return podatak110;
    }

    /**
     * Sets the value of the podatak110 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak110(BigDecimal value) {
        this.podatak110 = value;
    }

    /**
     * Gets the value of the podatak200 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak200() {
        return podatak200;
    }

    /**
     * Sets the value of the podatak200 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak200(SIsporuka value) {
        this.podatak200 = value;
    }

    /**
     * Gets the value of the podatak201 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak201() {
        return podatak201;
    }

    /**
     * Sets the value of the podatak201 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak201(SIsporuka value) {
        this.podatak201 = value;
    }

    /**
     * Gets the value of the podatak202 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak202() {
        return podatak202;
    }

    /**
     * Sets the value of the podatak202 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak202(SIsporuka value) {
        this.podatak202 = value;
    }

    /**
     * Gets the value of the podatak203 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak203() {
        return podatak203;
    }

    /**
     * Sets the value of the podatak203 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak203(SIsporuka value) {
        this.podatak203 = value;
    }

    /**
     * Gets the value of the podatak204 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak204() {
        return podatak204;
    }

    /**
     * Sets the value of the podatak204 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak204(SIsporuka value) {
        this.podatak204 = value;
    }

    /**
     * Gets the value of the podatak205 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak205() {
        return podatak205;
    }

    /**
     * Sets the value of the podatak205 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak205(SIsporuka value) {
        this.podatak205 = value;
    }

    /**
     * Gets the value of the podatak206 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak206() {
        return podatak206;
    }

    /**
     * Sets the value of the podatak206 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak206(SIsporuka value) {
        this.podatak206 = value;
    }

    /**
     * Gets the value of the podatak207 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak207() {
        return podatak207;
    }

    /**
     * Sets the value of the podatak207 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak207(SIsporuka value) {
        this.podatak207 = value;
    }

    /**
     * Gets the value of the podatak208 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak208() {
        return podatak208;
    }

    /**
     * Sets the value of the podatak208 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak208(SIsporuka value) {
        this.podatak208 = value;
    }

    /**
     * Gets the value of the podatak209 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak209() {
        return podatak209;
    }

    /**
     * Sets the value of the podatak209 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak209(SIsporuka value) {
        this.podatak209 = value;
    }

    /**
     * Gets the value of the podatak210 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak210() {
        return podatak210;
    }

    /**
     * Sets the value of the podatak210 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak210(SIsporuka value) {
        this.podatak210 = value;
    }

    /**
     * Gets the value of the podatak211 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak211() {
        return podatak211;
    }

    /**
     * Sets the value of the podatak211 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak211(SIsporuka value) {
        this.podatak211 = value;
    }

    /**
     * Gets the value of the podatak212 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak212() {
        return podatak212;
    }

    /**
     * Sets the value of the podatak212 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak212(SIsporuka value) {
        this.podatak212 = value;
    }

    /**
     * Gets the value of the podatak213 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak213() {
        return podatak213;
    }

    /**
     * Sets the value of the podatak213 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak213(SIsporuka value) {
        this.podatak213 = value;
    }

    /**
     * Gets the value of the podatak214 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak214() {
        return podatak214;
    }

    /**
     * Sets the value of the podatak214 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak214(SIsporuka value) {
        this.podatak214 = value;
    }

    /**
     * Gets the value of the podatak300 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak300() {
        return podatak300;
    }

    /**
     * Sets the value of the podatak300 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak300(SIsporuka value) {
        this.podatak300 = value;
    }

    /**
     * Gets the value of the podatak301 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak301() {
        return podatak301;
    }

    /**
     * Sets the value of the podatak301 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak301(SIsporuka value) {
        this.podatak301 = value;
    }

    /**
     * Gets the value of the podatak302 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak302() {
        return podatak302;
    }

    /**
     * Sets the value of the podatak302 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak302(SIsporuka value) {
        this.podatak302 = value;
    }

    /**
     * Gets the value of the podatak303 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak303() {
        return podatak303;
    }

    /**
     * Sets the value of the podatak303 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak303(SIsporuka value) {
        this.podatak303 = value;
    }

    /**
     * Gets the value of the podatak304 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak304() {
        return podatak304;
    }

    /**
     * Sets the value of the podatak304 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak304(SIsporuka value) {
        this.podatak304 = value;
    }

    /**
     * Gets the value of the podatak305 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak305() {
        return podatak305;
    }

    /**
     * Sets the value of the podatak305 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak305(SIsporuka value) {
        this.podatak305 = value;
    }

    /**
     * Gets the value of the podatak306 property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuka }
     *     
     */
    public SIsporuka getPodatak306() {
        return podatak306;
    }

    /**
     * Sets the value of the podatak306 property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuka }
     *     
     */
    public void setPodatak306(SIsporuka value) {
        this.podatak306 = value;
    }

    /**
     * Gets the value of the podatak307 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak307() {
        return podatak307;
    }

    /**
     * Sets the value of the podatak307 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak307(BigDecimal value) {
        this.podatak307 = value;
    }

    /**
     * Gets the value of the podatak400 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak400() {
        return podatak400;
    }

    /**
     * Sets the value of the podatak400 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak400(BigDecimal value) {
        this.podatak400 = value;
    }

    /**
     * Gets the value of the podatak500 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak500() {
        return podatak500;
    }

    /**
     * Sets the value of the podatak500 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak500(BigDecimal value) {
        this.podatak500 = value;
    }

    /**
     * Gets the value of the podatak600 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak600() {
        return podatak600;
    }

    /**
     * Sets the value of the podatak600 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak600(BigDecimal value) {
        this.podatak600 = value;
    }

    /**
     * Gets the value of the podatak700 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak700() {
        return podatak700;
    }

    /**
     * Sets the value of the podatak700 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak700(BigDecimal value) {
        this.podatak700 = value;
    }

    /**
     * Gets the value of the povrat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPovrat() {
        return povrat;
    }

    /**
     * Sets the value of the povrat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPovrat(BigDecimal value) {
        this.povrat = value;
    }

    /**
     * Gets the value of the predujam property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPredujam() {
        return predujam;
    }

    /**
     * Sets the value of the predujam property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPredujam(BigDecimal value) {
        this.predujam = value;
    }

    /**
     * Gets the value of the ustupPovrata property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUstupPovrata() {
        return ustupPovrata;
    }

    /**
     * Sets the value of the ustupPovrata property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUstupPovrata(BigDecimal value) {
        this.ustupPovrata = value;
    }

}
