//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.16 at 12:12:18 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.metapodaci.v2_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Primatelj dokumenta, npr. "Ministarstvo Financija, Porezna uprava, Zagreb"
 * 
 * <p>Java class for sAdresantTemeljni complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sAdresantTemeljni">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1>tOgraniceniZnakovniNizMin2Max128">
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sAdresantTemeljni", propOrder = {
    "value"
})
public class SAdresantTemeljni {

    @XmlValue
    protected String value;

    /**
     * Znakovni niz sa minimum 2 i maksimum 128 znakova
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
