//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.12 at 01:49:31 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.metapodaci.v2_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sMetapodaciElektronickogPotpisa complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sMetapodaciElektronickogPotpisa">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Datum" type="{http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0}sDatumTemeljni"/>
 *         &lt;element name="Identifikator" type="{http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0}sIdentifikatorTemeljni"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sMetapodaciElektronickogPotpisa", propOrder = {
    "datum",
    "identifikator"
})
public class SMetapodaciElektronickogPotpisa {

    @XmlElement(name = "Datum", required = true)
    protected SDatumTemeljni datum;
    @XmlElement(name = "Identifikator", required = true)
    protected SIdentifikatorTemeljni identifikator;

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link SDatumTemeljni }
     *     
     */
    public SDatumTemeljni getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link SDatumTemeljni }
     *     
     */
    public void setDatum(SDatumTemeljni value) {
        this.datum = value;
    }

    /**
     * Gets the value of the identifikator property.
     * 
     * @return
     *     possible object is
     *     {@link SIdentifikatorTemeljni }
     *     
     */
    public SIdentifikatorTemeljni getIdentifikator() {
        return identifikator;
    }

    /**
     * Sets the value of the identifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIdentifikatorTemeljni }
     *     
     */
    public void setIdentifikator(SIdentifikatorTemeljni value) {
        this.identifikator = value;
    }

}
