//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.16 at 12:12:18 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.metapodaci.v2_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Naslov elektroni?kog dokumenta. Primjerice "Obrazac PDV"
 * 
 * <p>Java class for sNaslovTemeljni complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sNaslovTemeljni">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1>tOgraniceniZnakovniNizMin2Max128">
 *       &lt;attribute name="dc" use="required" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOgraniceniZnakovniNizMin2Max128" fixed="http://purl.org/dc/elements/1.1/title" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sNaslovTemeljni", propOrder = {
    "value"
})
public class SNaslovTemeljni {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "dc", required = true)
    protected String dc;

    /**
     * Znakovni niz sa minimum 2 i maksimum 128 znakova
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the dc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDc() {
        if (dc == null) {
            return "http://purl.org/dc/elements/1.1/title";
        } else {
            return dc;
        }
    }

    /**
     * Sets the value of the dc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDc(String value) {
        this.dc = value;
    }

}
