//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.10 at 04:26:02 AM CET 
//


package hr.porezna_uprava.e_porezna.sheme.metapodaci.v2_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sPDVKmetapodaci complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sPDVKmetapodaci">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Naslov" type="{http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0}sNaslovTemeljni"/>
 *         &lt;element name="Autor" type="{http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0}sAutorTemeljni"/>
 *         &lt;element name="Datum" type="{http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0}sDatumTemeljni"/>
 *         &lt;element name="Format" type="{http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0}sFormatTemeljni"/>
 *         &lt;element name="Jezik" type="{http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0}sJezikTemeljni"/>
 *         &lt;element name="Identifikator" type="{http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0}sIdentifikatorTemeljni"/>
 *         &lt;element name="Uskladjenost" type="{http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0}sUskladjenost"/>
 *         &lt;element name="Tip" type="{http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0}sTipTemeljni"/>
 *         &lt;element name="Adresant" type="{http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0}sAdresantTemeljni"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sPDVKmetapodaci", propOrder = {
    "naslov",
    "autor",
    "datum",
    "format",
    "jezik",
    "identifikator",
    "uskladjenost",
    "tip",
    "adresant"
})
public class SPDVKmetapodaci {

    @XmlElement(name = "Naslov", required = true)
    protected SNaslovTemeljni naslov;
    @XmlElement(name = "Autor", required = true)
    protected SAutorTemeljni autor;
    @XmlElement(name = "Datum", required = true)
    protected SDatumTemeljni datum;
    @XmlElement(name = "Format", required = true)
    protected SFormatTemeljni format;
    @XmlElement(name = "Jezik", required = true)
    protected SJezikTemeljni jezik;
    @XmlElement(name = "Identifikator", required = true)
    protected SIdentifikatorTemeljni identifikator;
    @XmlElement(name = "Uskladjenost", required = true)
    protected SUskladjenost uskladjenost;
    @XmlElement(name = "Tip", required = true)
    protected STipTemeljni tip;
    @XmlElement(name = "Adresant", required = true)
    protected SAdresantTemeljni adresant;

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link SNaslovTemeljni }
     *     
     */
    public SNaslovTemeljni getNaslov() {
        return naslov;
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link SNaslovTemeljni }
     *     
     */
    public void setNaslov(SNaslovTemeljni value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the autor property.
     * 
     * @return
     *     possible object is
     *     {@link SAutorTemeljni }
     *     
     */
    public SAutorTemeljni getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAutorTemeljni }
     *     
     */
    public void setAutor(SAutorTemeljni value) {
        this.autor = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link SDatumTemeljni }
     *     
     */
    public SDatumTemeljni getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link SDatumTemeljni }
     *     
     */
    public void setDatum(SDatumTemeljni value) {
        this.datum = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link SFormatTemeljni }
     *     
     */
    public SFormatTemeljni getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFormatTemeljni }
     *     
     */
    public void setFormat(SFormatTemeljni value) {
        this.format = value;
    }

    /**
     * Gets the value of the jezik property.
     * 
     * @return
     *     possible object is
     *     {@link SJezikTemeljni }
     *     
     */
    public SJezikTemeljni getJezik() {
        return jezik;
    }

    /**
     * Sets the value of the jezik property.
     * 
     * @param value
     *     allowed object is
     *     {@link SJezikTemeljni }
     *     
     */
    public void setJezik(SJezikTemeljni value) {
        this.jezik = value;
    }

    /**
     * Gets the value of the identifikator property.
     * 
     * @return
     *     possible object is
     *     {@link SIdentifikatorTemeljni }
     *     
     */
    public SIdentifikatorTemeljni getIdentifikator() {
        return identifikator;
    }

    /**
     * Sets the value of the identifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIdentifikatorTemeljni }
     *     
     */
    public void setIdentifikator(SIdentifikatorTemeljni value) {
        this.identifikator = value;
    }

    /**
     * Gets the value of the uskladjenost property.
     * 
     * @return
     *     possible object is
     *     {@link SUskladjenost }
     *     
     */
    public SUskladjenost getUskladjenost() {
        return uskladjenost;
    }

    /**
     * Sets the value of the uskladjenost property.
     * 
     * @param value
     *     allowed object is
     *     {@link SUskladjenost }
     *     
     */
    public void setUskladjenost(SUskladjenost value) {
        this.uskladjenost = value;
    }

    /**
     * Gets the value of the tip property.
     * 
     * @return
     *     possible object is
     *     {@link STipTemeljni }
     *     
     */
    public STipTemeljni getTip() {
        return tip;
    }

    /**
     * Sets the value of the tip property.
     * 
     * @param value
     *     allowed object is
     *     {@link STipTemeljni }
     *     
     */
    public void setTip(STipTemeljni value) {
        this.tip = value;
    }

    /**
     * Gets the value of the adresant property.
     * 
     * @return
     *     possible object is
     *     {@link SAdresantTemeljni }
     *     
     */
    public SAdresantTemeljni getAdresant() {
        return adresant;
    }

    /**
     * Sets the value of the adresant property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAdresantTemeljni }
     *     
     */
    public void setAdresant(SAdresantTemeljni value) {
        this.adresant = value;
    }

}
