//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.12 at 01:49:31 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.metapodaci.v2_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.porezna_uprava.e_porezna.sheme.metapodaci.v2_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class URAObjectFactory {

    private final static QName _MetapodaciElektronickogPotpisa_QNAME = new QName("http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0", "MetapodaciElektronickogPotpisa");
    private final static QName _Metapodaci_QNAME = new QName("http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0", "Metapodaci");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.porezna_uprava.e_porezna.sheme.metapodaci.v2_0
     * 
     */
    public URAObjectFactory() {
    }

    /**
     * Create an instance of {@link SURAmetapodaci }
     * 
     */
    public SURAmetapodaci createSURAmetapodaci() {
        return new SURAmetapodaci();
    }

    /**
     * Create an instance of {@link SMetapodaciElektronickogPotpisa }
     * 
     */
    public SMetapodaciElektronickogPotpisa createSMetapodaciElektronickogPotpisa() {
        return new SMetapodaciElektronickogPotpisa();
    }

    /**
     * Create an instance of {@link SOdnosTemeljni }
     * 
     */
    public SOdnosTemeljni createSOdnosTemeljni() {
        return new SOdnosTemeljni();
    }

    /**
     * Create an instance of {@link SNaslovTemeljni }
     * 
     */
    public SNaslovTemeljni createSNaslovTemeljni() {
        return new SNaslovTemeljni();
    }

    /**
     * Create an instance of {@link STipTemeljni }
     * 
     */
    public STipTemeljni createSTipTemeljni() {
        return new STipTemeljni();
    }

    /**
     * Create an instance of {@link SIzvorTemeljni }
     * 
     */
    public SIzvorTemeljni createSIzvorTemeljni() {
        return new SIzvorTemeljni();
    }

    /**
     * Create an instance of {@link SUskladjenostTemeljni }
     * 
     */
    public SUskladjenostTemeljni createSUskladjenostTemeljni() {
        return new SUskladjenostTemeljni();
    }

    /**
     * Create an instance of {@link SDatumTemeljni }
     * 
     */
    public SDatumTemeljni createSDatumTemeljni() {
        return new SDatumTemeljni();
    }

    /**
     * Create an instance of {@link SAutorTemeljni }
     * 
     */
    public SAutorTemeljni createSAutorTemeljni() {
        return new SAutorTemeljni();
    }

    /**
     * Create an instance of {@link SIdentifikatorTemeljni }
     * 
     */
    public SIdentifikatorTemeljni createSIdentifikatorTemeljni() {
        return new SIdentifikatorTemeljni();
    }

    /**
     * Create an instance of {@link SJezikTemeljni }
     * 
     */
    public SJezikTemeljni createSJezikTemeljni() {
        return new SJezikTemeljni();
    }

    /**
     * Create an instance of {@link SUskladjenost }
     * 
     */
    public SUskladjenost createSUskladjenost() {
        return new SUskladjenost();
    }

    /**
     * Create an instance of {@link SAdresantTemeljni }
     * 
     */
    public SAdresantTemeljni createSAdresantTemeljni() {
        return new SAdresantTemeljni();
    }

    /**
     * Create an instance of {@link SFormatTemeljni }
     * 
     */
    public SFormatTemeljni createSFormatTemeljni() {
        return new SFormatTemeljni();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SMetapodaciElektronickogPotpisa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0", name = "MetapodaciElektronickogPotpisa")
    public JAXBElement<SMetapodaciElektronickogPotpisa> createMetapodaciElektronickogPotpisa(SMetapodaciElektronickogPotpisa value) {
        return new JAXBElement<SMetapodaciElektronickogPotpisa>(_MetapodaciElektronickogPotpisa_QNAME, SMetapodaciElektronickogPotpisa.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SURAmetapodaci }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0", name = "Metapodaci")
    public JAXBElement<SURAmetapodaci> createMetapodaci(SURAmetapodaci value) {
        return new JAXBElement<SURAmetapodaci>(_Metapodaci_QNAME, SURAmetapodaci.class, null, value);
    }

}
