//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 08:52:30 AM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacjoppd.v1_1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacjoppd.v1_1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ObrazacJOPPD_QNAME = new QName("http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1", "ObrazacJOPPD");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacjoppd.v1_1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SPrimatelji }
     * 
     */
    public SPrimatelji createSPrimatelji() {
        return new SPrimatelji();
    }

    /**
     * Create an instance of {@link SObrazacJOPPD }
     * 
     */
    public SObrazacJOPPD createSObrazacJOPPD() {
        return new SObrazacJOPPD();
    }

    /**
     * Create an instance of {@link SObveznikPlacanja }
     * 
     */
    public SObveznikPlacanja createSObveznikPlacanja() {
        return new SObveznikPlacanja();
    }

    /**
     * Create an instance of {@link SIzvjesceSastavio }
     * 
     */
    public SIzvjesceSastavio createSIzvjesceSastavio() {
        return new SIzvjesceSastavio();
    }

    /**
     * Create an instance of {@link SPredujamPoreza }
     * 
     */
    public SPredujamPoreza createSPredujamPoreza() {
        return new SPredujamPoreza();
    }

    /**
     * Create an instance of {@link SStranaA }
     * 
     */
    public SStranaA createSStranaA() {
        return new SStranaA();
    }

    /**
     * Create an instance of {@link SZaposljavanje }
     * 
     */
    public SZaposljavanje createSZaposljavanje() {
        return new SZaposljavanje();
    }

    /**
     * Create an instance of {@link SStranaB }
     * 
     */
    public SStranaB createSStranaB() {
        return new SStranaB();
    }

    /**
     * Create an instance of {@link SZdravstvenoOsiguranje }
     * 
     */
    public SZdravstvenoOsiguranje createSZdravstvenoOsiguranje() {
        return new SZdravstvenoOsiguranje();
    }

    /**
     * Create an instance of {@link SDoprinosi }
     * 
     */
    public SDoprinosi createSDoprinosi() {
        return new SDoprinosi();
    }

    /**
     * Create an instance of {@link SKapitaliziranaStednja }
     * 
     */
    public SKapitaliziranaStednja createSKapitaliziranaStednja() {
        return new SKapitaliziranaStednja();
    }

    /**
     * Create an instance of {@link SGeneracijskaSolidarnost }
     * 
     */
    public SGeneracijskaSolidarnost createSGeneracijskaSolidarnost() {
        return new SGeneracijskaSolidarnost();
    }

    /**
     * Create an instance of {@link SNaknadaZaposljavanjeInvalida }
     * 
     */
    public SNaknadaZaposljavanjeInvalida createSNaknadaZaposljavanjeInvalida() {
        return new SNaknadaZaposljavanjeInvalida();
    }

    /**
     * Create an instance of {@link SAdresa }
     * 
     */
    public SAdresa createSAdresa() {
        return new SAdresa();
    }

    /**
     * Create an instance of {@link SPodnositeljIzvjesca }
     * 
     */
    public SPodnositeljIzvjesca createSPodnositeljIzvjesca() {
        return new SPodnositeljIzvjesca();
    }

    /**
     * Create an instance of {@link SPrimatelji.P }
     * 
     */
    public SPrimatelji.P createSPrimateljiP() {
        return new SPrimatelji.P();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SObrazacJOPPD }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1", name = "ObrazacJOPPD")
    public JAXBElement<SObrazacJOPPD> createObrazacJOPPD(SObrazacJOPPD value) {
        return new JAXBElement<SObrazacJOPPD>(_ObrazacJOPPD_QNAME, SObrazacJOPPD.class, null, value);
    }

}
