//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 08:52:30 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacjoppd.v1_1;
