//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 08:52:30 AM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacjoppd.v1_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Doprinosi
 * 
 * <p>Java class for sDoprinosi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sDoprinosi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GeneracijskaSolidarnost" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}sGeneracijskaSolidarnost" minOccurs="0"/>
 *         &lt;element name="KapitaliziranaStednja" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}sKapitaliziranaStednja" minOccurs="0"/>
 *         &lt;element name="ZdravstvenoOsiguranje" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}sZdravstvenoOsiguranje" minOccurs="0"/>
 *         &lt;element name="Zaposljavanje" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}sZaposljavanje" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sDoprinosi", propOrder = {
    "generacijskaSolidarnost",
    "kapitaliziranaStednja",
    "zdravstvenoOsiguranje",
    "zaposljavanje"
})
public class SDoprinosi {

    @XmlElement(name = "GeneracijskaSolidarnost")
    protected SGeneracijskaSolidarnost generacijskaSolidarnost;
    @XmlElement(name = "KapitaliziranaStednja")
    protected SKapitaliziranaStednja kapitaliziranaStednja;
    @XmlElement(name = "ZdravstvenoOsiguranje")
    protected SZdravstvenoOsiguranje zdravstvenoOsiguranje;
    @XmlElement(name = "Zaposljavanje")
    protected SZaposljavanje zaposljavanje;

    /**
     * Gets the value of the generacijskaSolidarnost property.
     * 
     * @return
     *     possible object is
     *     {@link SGeneracijskaSolidarnost }
     *     
     */
    public SGeneracijskaSolidarnost getGeneracijskaSolidarnost() {
        return generacijskaSolidarnost;
    }

    /**
     * Sets the value of the generacijskaSolidarnost property.
     * 
     * @param value
     *     allowed object is
     *     {@link SGeneracijskaSolidarnost }
     *     
     */
    public void setGeneracijskaSolidarnost(SGeneracijskaSolidarnost value) {
        this.generacijskaSolidarnost = value;
    }

    /**
     * Gets the value of the kapitaliziranaStednja property.
     * 
     * @return
     *     possible object is
     *     {@link SKapitaliziranaStednja }
     *     
     */
    public SKapitaliziranaStednja getKapitaliziranaStednja() {
        return kapitaliziranaStednja;
    }

    /**
     * Sets the value of the kapitaliziranaStednja property.
     * 
     * @param value
     *     allowed object is
     *     {@link SKapitaliziranaStednja }
     *     
     */
    public void setKapitaliziranaStednja(SKapitaliziranaStednja value) {
        this.kapitaliziranaStednja = value;
    }

    /**
     * Gets the value of the zdravstvenoOsiguranje property.
     * 
     * @return
     *     possible object is
     *     {@link SZdravstvenoOsiguranje }
     *     
     */
    public SZdravstvenoOsiguranje getZdravstvenoOsiguranje() {
        return zdravstvenoOsiguranje;
    }

    /**
     * Sets the value of the zdravstvenoOsiguranje property.
     * 
     * @param value
     *     allowed object is
     *     {@link SZdravstvenoOsiguranje }
     *     
     */
    public void setZdravstvenoOsiguranje(SZdravstvenoOsiguranje value) {
        this.zdravstvenoOsiguranje = value;
    }

    /**
     * Gets the value of the zaposljavanje property.
     * 
     * @return
     *     possible object is
     *     {@link SZaposljavanje }
     *     
     */
    public SZaposljavanje getZaposljavanje() {
        return zaposljavanje;
    }

    /**
     * Sets the value of the zaposljavanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link SZaposljavanje }
     *     
     */
    public void setZaposljavanje(SZaposljavanje value) {
        this.zaposljavanje = value;
    }

}
