//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 08:52:30 AM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacjoppd.v1_1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * PODACI O NAKNADI UTVRĐENOJ SUKLADNO ODREDBAMA ZAKONA O PROFESIONALNOJ REHABILITACIJI I ZAPOŠLJAVANJU OSOBA S INVALIDITETOM
 * 
 * <p>Java class for sNaknadaZaposljavanjeInvalida complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sNaknadaZaposljavanjeInvalida">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="P1" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tBrojOsoba" minOccurs="0"/>
 *         &lt;element name="P2" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sNaknadaZaposljavanjeInvalida", propOrder = {
    "p1",
    "p2"
})
public class SNaknadaZaposljavanjeInvalida {

    @XmlElement(name = "P1")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer p1;
    @XmlElement(name = "P2")
    protected BigDecimal p2;

    /**
     * Gets the value of the p1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getP1() {
        return p1;
    }

    /**
     * Sets the value of the p1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setP1(Integer value) {
        this.p1 = value;
    }

    /**
     * Gets the value of the p2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP2() {
        return p2;
    }

    /**
     * Sets the value of the p2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP2(BigDecimal value) {
        this.p2 = value;
    }

}
