//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 08:52:30 AM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacjoppd.v1_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Podnositelj izvješća
 * 
 * <p>Java class for sPodnositeljIzvjesca complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sPodnositeljIzvjesca">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element name="Ime" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOgraniceniZnakovniNizMin2Max128"/>
 *             &lt;element name="Prezime" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOgraniceniZnakovniNizMin2Max128"/>
 *           &lt;/sequence>
 *           &lt;element name="Naziv" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOgraniceniZnakovniNizMin2Max128"/>
 *         &lt;/choice>
 *         &lt;element name="Adresa" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}sAdresa"/>
 *         &lt;element name="Email" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tEmail"/>
 *         &lt;element name="OIB" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOIB"/>
 *         &lt;element name="Oznaka" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaPodnositelja"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sPodnositeljIzvjesca", propOrder = {
    "ime",
    "prezime",
    "naziv",
    "adresa",
    "email",
    "oib",
    "oznaka"
})
public class SPodnositeljIzvjesca {

    @XmlElement(name = "Ime")
    protected String ime;
    @XmlElement(name = "Prezime")
    protected String prezime;
    @XmlElement(name = "Naziv")
    protected String naziv;
    @XmlElement(name = "Adresa", required = true)
    protected SAdresa adresa;
    @XmlElement(name = "Email", required = true)
    protected String email;
    @XmlElement(name = "OIB", required = true)
    protected String oib;
    @XmlElement(name = "Oznaka", required = true)
    protected String oznaka;

    /**
     * Gets the value of the ime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIme() {
        return ime;
    }

    /**
     * Sets the value of the ime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIme(String value) {
        this.ime = value;
    }

    /**
     * Gets the value of the prezime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrezime() {
        return prezime;
    }

    /**
     * Sets the value of the prezime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrezime(String value) {
        this.prezime = value;
    }

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the adresa property.
     * 
     * @return
     *     possible object is
     *     {@link SAdresa }
     *     
     */
    public SAdresa getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAdresa }
     *     
     */
    public void setAdresa(SAdresa value) {
        this.adresa = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the oib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOIB() {
        return oib;
    }

    /**
     * Sets the value of the oib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOIB(String value) {
        this.oib = value;
    }

    /**
     * Gets the value of the oznaka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOznaka() {
        return oznaka;
    }

    /**
     * Sets the value of the oznaka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOznaka(String value) {
        this.oznaka = value;
    }

}
