//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 08:52:30 AM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacjoppd.v1_1;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Podaci o primateljima
 * 
 * <p>Java class for sPrimatelji complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sPrimatelji">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="P" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="P1" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tRedniBroj"/>
 *                   &lt;element name="P2" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tSifraOpcineGrada"/>
 *                   &lt;element name="P3" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tSifraOpcineGrada"/>
 *                   &lt;element name="P4" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOIB"/>
 *                   &lt;element name="P5" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOgraniceniZnakovniNizMin2Max128"/>
 *                   &lt;element name="P61" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaStjecatelja"/>
 *                   &lt;element name="P62" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaPrimici"/>
 *                   &lt;element name="P71" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaMO"/>
 *                   &lt;element name="P72" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaInvaliditet"/>
 *                   &lt;element name="P8" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaMjesec"/>
 *                   &lt;element name="P9" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaRadnoVrijeme"/>
 *                   &lt;element name="P10" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tRadniSati"/>
 *                   &lt;element name="P100" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tRadniSati"/>
 *                   &lt;element name="P101" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="P102" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="P11" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P12" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P121" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P122" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P123" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P124" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P125" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P126" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P127" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P128" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P129" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P131" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P132" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P133" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P134" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *                   &lt;element name="P135" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *                   &lt;element name="P141" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *                   &lt;element name="P142" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *                   &lt;element name="P151" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaNeoporezivogPrimitka"/>
 *                   &lt;element name="P152" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                   &lt;element name="P161" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaNacinaIsplate"/>
 *                   &lt;element name="P162" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *                   &lt;element name="P17" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sPrimatelji", propOrder = {
    "p"
})
public class SPrimatelji {

    @XmlElement(name = "P")
    protected List<SPrimatelji.P> p;

    /**
     * Gets the value of the p property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the p property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getP().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SPrimatelji.P }
     * 
     * 
     */
    public List<SPrimatelji.P> getP() {
        if (p == null) {
            p = new ArrayList<SPrimatelji.P>();
        }
        return this.p;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="P1" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tRedniBroj"/>
     *         &lt;element name="P2" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tSifraOpcineGrada"/>
     *         &lt;element name="P3" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tSifraOpcineGrada"/>
     *         &lt;element name="P4" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOIB"/>
     *         &lt;element name="P5" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOgraniceniZnakovniNizMin2Max128"/>
     *         &lt;element name="P61" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaStjecatelja"/>
     *         &lt;element name="P62" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaPrimici"/>
     *         &lt;element name="P71" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaMO"/>
     *         &lt;element name="P72" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaInvaliditet"/>
     *         &lt;element name="P8" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaMjesec"/>
     *         &lt;element name="P9" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaRadnoVrijeme"/>
     *         &lt;element name="P10" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tRadniSati"/>
     *         &lt;element name="P100" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tRadniSati"/>
     *         &lt;element name="P101" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="P102" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="P11" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P12" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P121" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P122" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P123" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P124" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P125" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P126" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P127" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P128" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P129" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P131" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P132" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P133" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P134" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
     *         &lt;element name="P135" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
     *         &lt;element name="P141" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
     *         &lt;element name="P142" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
     *         &lt;element name="P151" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaNeoporezivogPrimitka"/>
     *         &lt;element name="P152" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *         &lt;element name="P161" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-1}tOznakaNacinaIsplate"/>
     *         &lt;element name="P162" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
     *         &lt;element name="P17" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "p1",
        "p2",
        "p3",
        "p4",
        "p5",
        "p61",
        "p62",
        "p71",
        "p72",
        "p8",
        "p9",
        "p10",
        "p100",
        "p101",
        "p102",
        "p11",
        "p12",
        "p121",
        "p122",
        "p123",
        "p124",
        "p125",
        "p126",
        "p127",
        "p128",
        "p129",
        "p131",
        "p132",
        "p133",
        "p134",
        "p135",
        "p141",
        "p142",
        "p151",
        "p152",
        "p161",
        "p162",
        "p17"
    })
    public static class P {

        @XmlElement(name = "P1")
        protected long p1;
        @XmlElement(name = "P2", required = true)
        protected String p2;
        @XmlElement(name = "P3", required = true)
        protected String p3;
        @XmlElement(name = "P4", required = true)
        protected String p4;
        @XmlElement(name = "P5", required = true)
        protected String p5;
        @XmlElement(name = "P61", required = true)
        protected String p61;
        @XmlElement(name = "P62", required = true)
        protected String p62;
        @XmlElement(name = "P71", required = true)
        protected String p71;
        @XmlElement(name = "P72", required = true)
        protected String p72;
        @XmlElement(name = "P8", required = true)
        protected String p8;
        @XmlElement(name = "P9", required = true)
        protected String p9;
        @XmlElement(name = "P10")
        protected int p10;
        @XmlElement(name = "P100")
        protected int p100;
        @XmlElement(name = "P101", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar p101;
        @XmlElement(name = "P102", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar p102;
        @XmlElement(name = "P11", required = true)
        protected BigDecimal p11;
        @XmlElement(name = "P12", required = true)
        protected BigDecimal p12;
        @XmlElement(name = "P121", required = true)
        protected BigDecimal p121;
        @XmlElement(name = "P122", required = true)
        protected BigDecimal p122;
        @XmlElement(name = "P123", required = true)
        protected BigDecimal p123;
        @XmlElement(name = "P124", required = true)
        protected BigDecimal p124;
        @XmlElement(name = "P125", required = true)
        protected BigDecimal p125;
        @XmlElement(name = "P126", required = true)
        protected BigDecimal p126;
        @XmlElement(name = "P127", required = true)
        protected BigDecimal p127;
        @XmlElement(name = "P128", required = true)
        protected BigDecimal p128;
        @XmlElement(name = "P129", required = true)
        protected BigDecimal p129;
        @XmlElement(name = "P131", required = true)
        protected BigDecimal p131;
        @XmlElement(name = "P132", required = true)
        protected BigDecimal p132;
        @XmlElement(name = "P133", required = true)
        protected BigDecimal p133;
        @XmlElement(name = "P134", required = true)
        protected BigDecimal p134;
        @XmlElement(name = "P135", required = true)
        protected BigDecimal p135;
        @XmlElement(name = "P141", required = true)
        protected BigDecimal p141;
        @XmlElement(name = "P142", required = true)
        protected BigDecimal p142;
        @XmlElement(name = "P151", required = true)
        protected String p151;
        @XmlElement(name = "P152", required = true)
        protected BigDecimal p152;
        @XmlElement(name = "P161", required = true)
        protected String p161;
        @XmlElement(name = "P162", required = true)
        protected BigDecimal p162;
        @XmlElement(name = "P17", required = true)
        protected BigDecimal p17;

        /**
         * Gets the value of the p1 property.
         * 
         */
        public long getP1() {
            return p1;
        }

        /**
         * Sets the value of the p1 property.
         * 
         */
        public void setP1(long value) {
            this.p1 = value;
        }

        /**
         * Gets the value of the p2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP2() {
            return p2;
        }

        /**
         * Sets the value of the p2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP2(String value) {
            this.p2 = value;
        }

        /**
         * Gets the value of the p3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP3() {
            return p3;
        }

        /**
         * Sets the value of the p3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP3(String value) {
            this.p3 = value;
        }

        /**
         * Gets the value of the p4 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP4() {
            return p4;
        }

        /**
         * Sets the value of the p4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP4(String value) {
            this.p4 = value;
        }

        /**
         * Gets the value of the p5 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP5() {
            return p5;
        }

        /**
         * Sets the value of the p5 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP5(String value) {
            this.p5 = value;
        }

        /**
         * Gets the value of the p61 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP61() {
            return p61;
        }

        /**
         * Sets the value of the p61 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP61(String value) {
            this.p61 = value;
        }

        /**
         * Gets the value of the p62 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP62() {
            return p62;
        }

        /**
         * Sets the value of the p62 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP62(String value) {
            this.p62 = value;
        }

        /**
         * Gets the value of the p71 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP71() {
            return p71;
        }

        /**
         * Sets the value of the p71 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP71(String value) {
            this.p71 = value;
        }

        /**
         * Gets the value of the p72 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP72() {
            return p72;
        }

        /**
         * Sets the value of the p72 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP72(String value) {
            this.p72 = value;
        }

        /**
         * Gets the value of the p8 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP8() {
            return p8;
        }

        /**
         * Sets the value of the p8 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP8(String value) {
            this.p8 = value;
        }

        /**
         * Gets the value of the p9 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP9() {
            return p9;
        }

        /**
         * Sets the value of the p9 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP9(String value) {
            this.p9 = value;
        }

        /**
         * Gets the value of the p10 property.
         * 
         */
        public int getP10() {
            return p10;
        }

        /**
         * Sets the value of the p10 property.
         * 
         */
        public void setP10(int value) {
            this.p10 = value;
        }

        /**
         * Gets the value of the p100 property.
         * 
         */
        public int getP100() {
            return p100;
        }

        /**
         * Sets the value of the p100 property.
         * 
         */
        public void setP100(int value) {
            this.p100 = value;
        }

        /**
         * Gets the value of the p101 property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getP101() {
            return p101;
        }

        /**
         * Sets the value of the p101 property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setP101(XMLGregorianCalendar value) {
            this.p101 = value;
        }

        /**
         * Gets the value of the p102 property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getP102() {
            return p102;
        }

        /**
         * Sets the value of the p102 property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setP102(XMLGregorianCalendar value) {
            this.p102 = value;
        }

        /**
         * Gets the value of the p11 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP11() {
            return p11;
        }

        /**
         * Sets the value of the p11 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP11(BigDecimal value) {
            this.p11 = value;
        }

        /**
         * Gets the value of the p12 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP12() {
            return p12;
        }

        /**
         * Sets the value of the p12 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP12(BigDecimal value) {
            this.p12 = value;
        }

        /**
         * Gets the value of the p121 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP121() {
            return p121;
        }

        /**
         * Sets the value of the p121 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP121(BigDecimal value) {
            this.p121 = value;
        }

        /**
         * Gets the value of the p122 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP122() {
            return p122;
        }

        /**
         * Sets the value of the p122 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP122(BigDecimal value) {
            this.p122 = value;
        }

        /**
         * Gets the value of the p123 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP123() {
            return p123;
        }

        /**
         * Sets the value of the p123 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP123(BigDecimal value) {
            this.p123 = value;
        }

        /**
         * Gets the value of the p124 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP124() {
            return p124;
        }

        /**
         * Sets the value of the p124 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP124(BigDecimal value) {
            this.p124 = value;
        }

        /**
         * Gets the value of the p125 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP125() {
            return p125;
        }

        /**
         * Sets the value of the p125 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP125(BigDecimal value) {
            this.p125 = value;
        }

        /**
         * Gets the value of the p126 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP126() {
            return p126;
        }

        /**
         * Sets the value of the p126 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP126(BigDecimal value) {
            this.p126 = value;
        }

        /**
         * Gets the value of the p127 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP127() {
            return p127;
        }

        /**
         * Sets the value of the p127 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP127(BigDecimal value) {
            this.p127 = value;
        }

        /**
         * Gets the value of the p128 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP128() {
            return p128;
        }

        /**
         * Sets the value of the p128 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP128(BigDecimal value) {
            this.p128 = value;
        }

        /**
         * Gets the value of the p129 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP129() {
            return p129;
        }

        /**
         * Sets the value of the p129 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP129(BigDecimal value) {
            this.p129 = value;
        }

        /**
         * Gets the value of the p131 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP131() {
            return p131;
        }

        /**
         * Sets the value of the p131 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP131(BigDecimal value) {
            this.p131 = value;
        }

        /**
         * Gets the value of the p132 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP132() {
            return p132;
        }

        /**
         * Sets the value of the p132 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP132(BigDecimal value) {
            this.p132 = value;
        }

        /**
         * Gets the value of the p133 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP133() {
            return p133;
        }

        /**
         * Sets the value of the p133 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP133(BigDecimal value) {
            this.p133 = value;
        }

        /**
         * Gets the value of the p134 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP134() {
            return p134;
        }

        /**
         * Sets the value of the p134 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP134(BigDecimal value) {
            this.p134 = value;
        }

        /**
         * Gets the value of the p135 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP135() {
            return p135;
        }

        /**
         * Sets the value of the p135 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP135(BigDecimal value) {
            this.p135 = value;
        }

        /**
         * Gets the value of the p141 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP141() {
            return p141;
        }

        /**
         * Sets the value of the p141 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP141(BigDecimal value) {
            this.p141 = value;
        }

        /**
         * Gets the value of the p142 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP142() {
            return p142;
        }

        /**
         * Sets the value of the p142 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP142(BigDecimal value) {
            this.p142 = value;
        }

        /**
         * Gets the value of the p151 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP151() {
            return p151;
        }

        /**
         * Sets the value of the p151 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP151(String value) {
            this.p151 = value;
        }

        /**
         * Gets the value of the p152 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP152() {
            return p152;
        }

        /**
         * Sets the value of the p152 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP152(BigDecimal value) {
            this.p152 = value;
        }

        /**
         * Gets the value of the p161 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP161() {
            return p161;
        }

        /**
         * Sets the value of the p161 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP161(String value) {
            this.p161 = value;
        }

        /**
         * Gets the value of the p162 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP162() {
            return p162;
        }

        /**
         * Sets the value of the p162 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP162(BigDecimal value) {
            this.p162 = value;
        }

        /**
         * Gets the value of the p17 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getP17() {
            return p17;
        }

        /**
         * Sets the value of the p17 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setP17(BigDecimal value) {
            this.p17 = value;
        }

    }

}
