//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 08:52:30 AM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacjoppd.v1_1;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Zdravstveno osiguranje
 * 
 * <p>Java class for sZdravstvenoOsiguranje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sZdravstvenoOsiguranje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="P1" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2" minOccurs="0"/>
 *         &lt;element name="P2" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2" minOccurs="0"/>
 *         &lt;element name="P3" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2" minOccurs="0"/>
 *         &lt;element name="P4" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2" minOccurs="0"/>
 *         &lt;element name="P5" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2" minOccurs="0"/>
 *         &lt;element name="P6" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2" minOccurs="0"/>
 *         &lt;element name="P7" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2" minOccurs="0"/>
 *         &lt;element name="P8" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2" minOccurs="0"/>
 *         &lt;element name="P9" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2" minOccurs="0"/>
 *         &lt;element name="P10" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2" minOccurs="0"/>
 *         &lt;element name="P11" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2" minOccurs="0"/>
 *         &lt;element name="P12" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sZdravstvenoOsiguranje", propOrder = {
    "p1",
    "p2",
    "p3",
    "p4",
    "p5",
    "p6",
    "p7",
    "p8",
    "p9",
    "p10",
    "p11",
    "p12"
})
public class SZdravstvenoOsiguranje {

    @XmlElement(name = "P1")
    protected BigDecimal p1;
    @XmlElement(name = "P2")
    protected BigDecimal p2;
    @XmlElement(name = "P3")
    protected BigDecimal p3;
    @XmlElement(name = "P4")
    protected BigDecimal p4;
    @XmlElement(name = "P5")
    protected BigDecimal p5;
    @XmlElement(name = "P6")
    protected BigDecimal p6;
    @XmlElement(name = "P7")
    protected BigDecimal p7;
    @XmlElement(name = "P8")
    protected BigDecimal p8;
    @XmlElement(name = "P9")
    protected BigDecimal p9;
    @XmlElement(name = "P10")
    protected BigDecimal p10;
    @XmlElement(name = "P11")
    protected BigDecimal p11;
    @XmlElement(name = "P12")
    protected BigDecimal p12;

    /**
     * Gets the value of the p1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP1() {
        return p1;
    }

    /**
     * Sets the value of the p1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP1(BigDecimal value) {
        this.p1 = value;
    }

    /**
     * Gets the value of the p2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP2() {
        return p2;
    }

    /**
     * Sets the value of the p2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP2(BigDecimal value) {
        this.p2 = value;
    }

    /**
     * Gets the value of the p3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP3() {
        return p3;
    }

    /**
     * Sets the value of the p3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP3(BigDecimal value) {
        this.p3 = value;
    }

    /**
     * Gets the value of the p4 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP4() {
        return p4;
    }

    /**
     * Sets the value of the p4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP4(BigDecimal value) {
        this.p4 = value;
    }

    /**
     * Gets the value of the p5 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP5() {
        return p5;
    }

    /**
     * Sets the value of the p5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP5(BigDecimal value) {
        this.p5 = value;
    }

    /**
     * Gets the value of the p6 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP6() {
        return p6;
    }

    /**
     * Sets the value of the p6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP6(BigDecimal value) {
        this.p6 = value;
    }

    /**
     * Gets the value of the p7 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP7() {
        return p7;
    }

    /**
     * Sets the value of the p7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP7(BigDecimal value) {
        this.p7 = value;
    }

    /**
     * Gets the value of the p8 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP8() {
        return p8;
    }

    /**
     * Sets the value of the p8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP8(BigDecimal value) {
        this.p8 = value;
    }

    /**
     * Gets the value of the p9 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP9() {
        return p9;
    }

    /**
     * Sets the value of the p9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP9(BigDecimal value) {
        this.p9 = value;
    }

    /**
     * Gets the value of the p10 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP10() {
        return p10;
    }

    /**
     * Sets the value of the p10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP10(BigDecimal value) {
        this.p10 = value;
    }

    /**
     * Gets the value of the p11 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP11() {
        return p11;
    }

    /**
     * Sets the value of the p11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP11(BigDecimal value) {
        this.p11 = value;
    }

    /**
     * Gets the value of the p12 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getP12() {
        return p12;
    }

    /**
     * Sets the value of the p12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setP12(BigDecimal value) {
        this.p12 = value;
    }

}
