//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.03 at 02:46:02 PM CEST 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazaczp.v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazaczp.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ObrazacZP_QNAME = new QName("http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacZP/v1-0", "ObrazacZP");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazaczp.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link STijelo }
     * 
     */
    public STijelo createSTijelo() {
        return new STijelo();
    }

    /**
     * Create an instance of {@link SObrazacZP }
     * 
     */
    public SObrazacZP createSObrazacZP() {
        return new SObrazacZP();
    }

    /**
     * Create an instance of {@link SIsporuka }
     * 
     */
    public SIsporuka createSIsporuka() {
        return new SIsporuka();
    }

    /**
     * Create an instance of {@link SIsporukeUkupno }
     * 
     */
    public SIsporukeUkupno createSIsporukeUkupno() {
        return new SIsporukeUkupno();
    }

    /**
     * Create an instance of {@link SRazdoblje }
     * 
     */
    public SRazdoblje createSRazdoblje() {
        return new SRazdoblje();
    }

    /**
     * Create an instance of {@link SObracunSastavio }
     * 
     */
    public SObracunSastavio createSObracunSastavio() {
        return new SObracunSastavio();
    }

    /**
     * Create an instance of {@link SPoslovniSubjekt }
     * 
     */
    public SPoslovniSubjekt createSPoslovniSubjekt() {
        return new SPoslovniSubjekt();
    }

    /**
     * Create an instance of {@link SZaglavlje }
     * 
     */
    public SZaglavlje createSZaglavlje() {
        return new SZaglavlje();
    }

    /**
     * Create an instance of {@link SZastupnik }
     * 
     */
    public SZastupnik createSZastupnik() {
        return new SZastupnik();
    }

    /**
     * Create an instance of {@link SPoslovniSubjektProsireno }
     * 
     */
    public SPoslovniSubjektProsireno createSPoslovniSubjektProsireno() {
        return new SPoslovniSubjektProsireno();
    }

    /**
     * Create an instance of {@link SAdresa }
     * 
     */
    public SAdresa createSAdresa() {
        return new SAdresa();
    }

    /**
     * Create an instance of {@link STijelo.Isporuke }
     * 
     */
    public STijelo.Isporuke createSTijeloIsporuke() {
        return new STijelo.Isporuke();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SObrazacZP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacZP/v1-0", name = "ObrazacZP")
    public JAXBElement<SObrazacZP> createObrazacZP(SObrazacZP value) {
        return new JAXBElement<SObrazacZP>(_ObrazacZP_QNAME, SObrazacZP.class, null, value);
    }

}
