//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.08 at 10:19:02 AM CEST 
//


package hr.fina.eracun.b2g.pki.sendb2goutgoinginvoice.v0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.fina.eracun.b2g.pki.sendb2goutgoinginvoice.v0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.fina.eracun.b2g.pki.sendb2goutgoinginvoice.v0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SendB2GOutgoingInvoiceMsg }
     * 
     */
    public SendB2GOutgoingInvoiceMsg createSendB2GOutgoingInvoiceMsg() {
        return new SendB2GOutgoingInvoiceMsg();
    }

    /**
     * Create an instance of {@link SendB2GOutgoingInvoiceAckMsg }
     * 
     */
    public SendB2GOutgoingInvoiceAckMsg createSendB2GOutgoingInvoiceAckMsg() {
        return new SendB2GOutgoingInvoiceAckMsg();
    }

    /**
     * Create an instance of {@link SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope }
     * 
     */
    public SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope createSendB2GOutgoingInvoiceAckMsgB2GOutgoingInvoiceEnvelope() {
        return new SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope();
    }

    /**
     * Create an instance of {@link SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing }
     * 
     */
    public SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing createSendB2GOutgoingInvoiceAckMsgB2GOutgoingInvoiceEnvelopeB2GOutgoingInvoiceProcessing() {
        return new SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing();
    }

    /**
     * Create an instance of {@link SendB2GOutgoingInvoiceMsg.Data }
     * 
     */
    public SendB2GOutgoingInvoiceMsg.Data createSendB2GOutgoingInvoiceMsgData() {
        return new SendB2GOutgoingInvoiceMsg.Data();
    }

    /**
     * Create an instance of {@link SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.CorrectB2GOutgoingInvoice }
     * 
     */
    public SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.CorrectB2GOutgoingInvoice createSendB2GOutgoingInvoiceAckMsgB2GOutgoingInvoiceEnvelopeB2GOutgoingInvoiceProcessingCorrectB2GOutgoingInvoice() {
        return new SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.CorrectB2GOutgoingInvoice();
    }

    /**
     * Create an instance of {@link SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.IncorrectB2GOutgoingInvoice }
     * 
     */
    public SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.IncorrectB2GOutgoingInvoice createSendB2GOutgoingInvoiceAckMsgB2GOutgoingInvoiceEnvelopeB2GOutgoingInvoiceProcessingIncorrectB2GOutgoingInvoice() {
        return new SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.IncorrectB2GOutgoingInvoice();
    }

    /**
     * Create an instance of {@link SendB2GOutgoingInvoiceMsg.Data.B2GOutgoingInvoiceEnvelope }
     * 
     */
    public SendB2GOutgoingInvoiceMsg.Data.B2GOutgoingInvoiceEnvelope createSendB2GOutgoingInvoiceMsgDataB2GOutgoingInvoiceEnvelope() {
        return new SendB2GOutgoingInvoiceMsg.Data.B2GOutgoingInvoiceEnvelope();
    }

}
