//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.08 at 10:19:02 AM CEST 
//


package hr.fina.eracun.b2g.pki.sendb2goutgoinginvoice.v0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import hr.fina.eracun.b2g.invoicewebservicecomponents.v0.HeaderSupplierType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1}HeaderSupplier"/>
 *         &lt;element name="Data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="B2GOutgoingInvoiceEnvelope">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="XMLStandard">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="UBL"/>
 *                                   &lt;enumeration value="CII"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="SpecificationIdentifier">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="urn:cen.eu:en16931:2017"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="BuyerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AdditionalBuyerID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;choice>
 *                               &lt;element name="InvoiceEnvelope" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                               &lt;element name="CreditNoteEnvelope" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *                             &lt;/choice>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "headerSupplier",
    "data"
})
@XmlRootElement(name = "SendB2GOutgoingInvoiceMsg")
public class SendB2GOutgoingInvoiceMsg {

    @XmlElement(name = "HeaderSupplier", namespace = "http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", required = true)
    protected HeaderSupplierType headerSupplier;
    @XmlElement(name = "Data", required = true)
    protected SendB2GOutgoingInvoiceMsg.Data data;

    /**
     * Zaglavlje poruke
     * 
     * @return
     *     possible object is
     *     {@link HeaderSupplierType }
     *     
     */
    public HeaderSupplierType getHeaderSupplier() {
        return headerSupplier;
    }

    /**
     * Sets the value of the headerSupplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderSupplierType }
     *     
     */
    public void setHeaderSupplier(HeaderSupplierType value) {
        this.headerSupplier = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link SendB2GOutgoingInvoiceMsg.Data }
     *     
     */
    public SendB2GOutgoingInvoiceMsg.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendB2GOutgoingInvoiceMsg.Data }
     *     
     */
    public void setData(SendB2GOutgoingInvoiceMsg.Data value) {
        this.data = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="B2GOutgoingInvoiceEnvelope">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="XMLStandard">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="UBL"/>
     *                         &lt;enumeration value="CII"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="SpecificationIdentifier">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="urn:cen.eu:en16931:2017"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="BuyerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AdditionalBuyerID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;choice>
     *                     &lt;element name="InvoiceEnvelope" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
     *                     &lt;element name="CreditNoteEnvelope" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
     *                   &lt;/choice>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "b2GOutgoingInvoiceEnvelope"
    })
    public static class Data {

        @XmlElement(name = "B2GOutgoingInvoiceEnvelope", required = true)
        protected SendB2GOutgoingInvoiceMsg.Data.B2GOutgoingInvoiceEnvelope b2GOutgoingInvoiceEnvelope;

        /**
         * Gets the value of the b2GOutgoingInvoiceEnvelope property.
         * 
         * @return
         *     possible object is
         *     {@link SendB2GOutgoingInvoiceMsg.Data.B2GOutgoingInvoiceEnvelope }
         *     
         */
        public SendB2GOutgoingInvoiceMsg.Data.B2GOutgoingInvoiceEnvelope getB2GOutgoingInvoiceEnvelope() {
            return b2GOutgoingInvoiceEnvelope;
        }

        /**
         * Sets the value of the b2GOutgoingInvoiceEnvelope property.
         * 
         * @param value
         *     allowed object is
         *     {@link SendB2GOutgoingInvoiceMsg.Data.B2GOutgoingInvoiceEnvelope }
         *     
         */
        public void setB2GOutgoingInvoiceEnvelope(SendB2GOutgoingInvoiceMsg.Data.B2GOutgoingInvoiceEnvelope value) {
            this.b2GOutgoingInvoiceEnvelope = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="XMLStandard">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="UBL"/>
         *               &lt;enumeration value="CII"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="SpecificationIdentifier">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="urn:cen.eu:en16931:2017"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="BuyerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AdditionalBuyerID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;choice>
         *           &lt;element name="InvoiceEnvelope" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
         *           &lt;element name="CreditNoteEnvelope" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
         *         &lt;/choice>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "xmlStandard",
            "specificationIdentifier",
            "supplierInvoiceID",
            "buyerID",
            "additionalBuyerID",
            "invoiceEnvelope",
            "creditNoteEnvelope"
        })
        public static class B2GOutgoingInvoiceEnvelope {

            @XmlElement(name = "XMLStandard", required = true)
            protected String xmlStandard;
            @XmlElement(name = "SpecificationIdentifier", required = true)
            protected String specificationIdentifier;
            @XmlElement(name = "SupplierInvoiceID", required = true)
            protected String supplierInvoiceID;
            @XmlElement(name = "BuyerID", required = true)
            protected String buyerID;
            @XmlElement(name = "AdditionalBuyerID")
            protected String additionalBuyerID;
            @XmlElement(name = "InvoiceEnvelope")
            protected byte[] invoiceEnvelope;
            @XmlElement(name = "CreditNoteEnvelope")
            protected byte[] creditNoteEnvelope;

            /**
             * Gets the value of the xmlStandard property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXMLStandard() {
                return xmlStandard;
            }

            /**
             * Sets the value of the xmlStandard property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXMLStandard(String value) {
                this.xmlStandard = value;
            }

            /**
             * Gets the value of the specificationIdentifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSpecificationIdentifier() {
                return specificationIdentifier;
            }

            /**
             * Sets the value of the specificationIdentifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSpecificationIdentifier(String value) {
                this.specificationIdentifier = value;
            }

            /**
             * Gets the value of the supplierInvoiceID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSupplierInvoiceID() {
                return supplierInvoiceID;
            }

            /**
             * Sets the value of the supplierInvoiceID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSupplierInvoiceID(String value) {
                this.supplierInvoiceID = value;
            }

            /**
             * Gets the value of the buyerID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBuyerID() {
                return buyerID;
            }

            /**
             * Sets the value of the buyerID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBuyerID(String value) {
                this.buyerID = value;
            }

            /**
             * Gets the value of the additionalBuyerID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdditionalBuyerID() {
                return additionalBuyerID;
            }

            /**
             * Sets the value of the additionalBuyerID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdditionalBuyerID(String value) {
                this.additionalBuyerID = value;
            }

            /**
             * Gets the value of the invoiceEnvelope property.
             * 
             * @return
             *     possible object is
             *     byte[]
             */
            public byte[] getInvoiceEnvelope() {
                return invoiceEnvelope;
            }

            /**
             * Sets the value of the invoiceEnvelope property.
             * 
             * @param value
             *     allowed object is
             *     byte[]
             */
            public void setInvoiceEnvelope(byte[] value) {
                this.invoiceEnvelope = value;
            }

            /**
             * Gets the value of the creditNoteEnvelope property.
             * 
             * @return
             *     possible object is
             *     byte[]
             */
            public byte[] getCreditNoteEnvelope() {
                return creditNoteEnvelope;
            }

            /**
             * Sets the value of the creditNoteEnvelope property.
             * 
             * @param value
             *     allowed object is
             *     byte[]
             */
            public void setCreditNoteEnvelope(byte[] value) {
                this.creditNoteEnvelope = value;
            }

        }

    }

}
