//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.08 at 10:19:02 AM CEST 
//


package hr.fina.eracun.b2g.pki.sendb2goutgoinginvoice.v0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import hr.fina.eracun.b2g.invoicewebservicecomponents.v0.MessageAckType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1}MessageAck"/>
 *         &lt;element name="B2GOutgoingInvoiceEnvelope" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="B2GOutgoingInvoiceProcessing">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="CorrectB2GOutgoingInvoice">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="InvoiceID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                       &lt;element name="InvoiceTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="IncorrectB2GOutgoingInvoice">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageAck",
    "b2GOutgoingInvoiceEnvelope"
})
@XmlRootElement(name = "SendB2GOutgoingInvoiceAckMsg")
public class SendB2GOutgoingInvoiceAckMsg {

    @XmlElement(name = "MessageAck", namespace = "http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", required = true)
    protected MessageAckType messageAck;
    @XmlElement(name = "B2GOutgoingInvoiceEnvelope")
    protected SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope b2GOutgoingInvoiceEnvelope;

    /**
     * Gets the value of the messageAck property.
     * 
     * @return
     *     possible object is
     *     {@link MessageAckType }
     *     
     */
    public MessageAckType getMessageAck() {
        return messageAck;
    }

    /**
     * Sets the value of the messageAck property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageAckType }
     *     
     */
    public void setMessageAck(MessageAckType value) {
        this.messageAck = value;
    }

    /**
     * Gets the value of the b2GOutgoingInvoiceEnvelope property.
     * 
     * @return
     *     possible object is
     *     {@link SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope }
     *     
     */
    public SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope getB2GOutgoingInvoiceEnvelope() {
        return b2GOutgoingInvoiceEnvelope;
    }

    /**
     * Sets the value of the b2GOutgoingInvoiceEnvelope property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope }
     *     
     */
    public void setB2GOutgoingInvoiceEnvelope(SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope value) {
        this.b2GOutgoingInvoiceEnvelope = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="B2GOutgoingInvoiceProcessing">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="CorrectB2GOutgoingInvoice">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="InvoiceID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                             &lt;element name="InvoiceTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="IncorrectB2GOutgoingInvoice">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "b2GOutgoingInvoiceProcessing"
    })
    public static class B2GOutgoingInvoiceEnvelope {

        @XmlElement(name = "B2GOutgoingInvoiceProcessing", required = true)
        protected SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing b2GOutgoingInvoiceProcessing;

        /**
         * Gets the value of the b2GOutgoingInvoiceProcessing property.
         * 
         * @return
         *     possible object is
         *     {@link SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing }
         *     
         */
        public SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing getB2GOutgoingInvoiceProcessing() {
            return b2GOutgoingInvoiceProcessing;
        }

        /**
         * Sets the value of the b2GOutgoingInvoiceProcessing property.
         * 
         * @param value
         *     allowed object is
         *     {@link SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing }
         *     
         */
        public void setB2GOutgoingInvoiceProcessing(SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing value) {
            this.b2GOutgoingInvoiceProcessing = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="CorrectB2GOutgoingInvoice">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="InvoiceID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                   &lt;element name="InvoiceTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="IncorrectB2GOutgoingInvoice">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "correctB2GOutgoingInvoice",
            "incorrectB2GOutgoingInvoice"
        })
        public static class B2GOutgoingInvoiceProcessing {

            @XmlElement(name = "CorrectB2GOutgoingInvoice")
            protected SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.CorrectB2GOutgoingInvoice correctB2GOutgoingInvoice;
            @XmlElement(name = "IncorrectB2GOutgoingInvoice")
            protected SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.IncorrectB2GOutgoingInvoice incorrectB2GOutgoingInvoice;

            /**
             * Gets the value of the correctB2GOutgoingInvoice property.
             * 
             * @return
             *     possible object is
             *     {@link SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.CorrectB2GOutgoingInvoice }
             *     
             */
            public SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.CorrectB2GOutgoingInvoice getCorrectB2GOutgoingInvoice() {
                return correctB2GOutgoingInvoice;
            }

            /**
             * Sets the value of the correctB2GOutgoingInvoice property.
             * 
             * @param value
             *     allowed object is
             *     {@link SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.CorrectB2GOutgoingInvoice }
             *     
             */
            public void setCorrectB2GOutgoingInvoice(SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.CorrectB2GOutgoingInvoice value) {
                this.correctB2GOutgoingInvoice = value;
            }

            /**
             * Gets the value of the incorrectB2GOutgoingInvoice property.
             * 
             * @return
             *     possible object is
             *     {@link SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.IncorrectB2GOutgoingInvoice }
             *     
             */
            public SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.IncorrectB2GOutgoingInvoice getIncorrectB2GOutgoingInvoice() {
                return incorrectB2GOutgoingInvoice;
            }

            /**
             * Sets the value of the incorrectB2GOutgoingInvoice property.
             * 
             * @param value
             *     allowed object is
             *     {@link SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.IncorrectB2GOutgoingInvoice }
             *     
             */
            public void setIncorrectB2GOutgoingInvoice(SendB2GOutgoingInvoiceAckMsg.B2GOutgoingInvoiceEnvelope.B2GOutgoingInvoiceProcessing.IncorrectB2GOutgoingInvoice value) {
                this.incorrectB2GOutgoingInvoice = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="InvoiceID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *         &lt;element name="InvoiceTimestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "supplierInvoiceID",
                "invoiceID",
                "invoiceTimestamp"
            })
            public static class CorrectB2GOutgoingInvoice {

                @XmlElement(name = "SupplierInvoiceID", required = true)
                protected String supplierInvoiceID;
                @XmlElement(name = "InvoiceID", required = true)
                protected BigInteger invoiceID;
                @XmlElement(name = "InvoiceTimestamp", required = true)
                @XmlSchemaType(name = "dateTime")
                protected XMLGregorianCalendar invoiceTimestamp;

                /**
                 * Gets the value of the supplierInvoiceID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSupplierInvoiceID() {
                    return supplierInvoiceID;
                }

                /**
                 * Sets the value of the supplierInvoiceID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSupplierInvoiceID(String value) {
                    this.supplierInvoiceID = value;
                }

                /**
                 * Gets the value of the invoiceID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getInvoiceID() {
                    return invoiceID;
                }

                /**
                 * Sets the value of the invoiceID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setInvoiceID(BigInteger value) {
                    this.invoiceID = value;
                }

                /**
                 * Gets the value of the invoiceTimestamp property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getInvoiceTimestamp() {
                    return invoiceTimestamp;
                }

                /**
                 * Sets the value of the invoiceTimestamp property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setInvoiceTimestamp(XMLGregorianCalendar value) {
                    this.invoiceTimestamp = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ErrorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "supplierInvoiceID",
                "errorCode",
                "errorMessage"
            })
            public static class IncorrectB2GOutgoingInvoice {

                @XmlElement(name = "SupplierInvoiceID", required = true)
                protected String supplierInvoiceID;
                @XmlElement(name = "ErrorCode", required = true)
                protected String errorCode;
                @XmlElement(name = "ErrorMessage")
                protected String errorMessage;

                /**
                 * Gets the value of the supplierInvoiceID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSupplierInvoiceID() {
                    return supplierInvoiceID;
                }

                /**
                 * Sets the value of the supplierInvoiceID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSupplierInvoiceID(String value) {
                    this.supplierInvoiceID = value;
                }

                /**
                 * Gets the value of the errorCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getErrorCode() {
                    return errorCode;
                }

                /**
                 * Sets the value of the errorCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setErrorCode(String value) {
                    this.errorCode = value;
                }

                /**
                 * Gets the value of the errorMessage property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getErrorMessage() {
                    return errorMessage;
                }

                /**
                 * Sets the value of the errorMessage property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setErrorMessage(String value) {
                    this.errorMessage = value;
                }

            }

        }

    }

}
