//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.10.07 at 11:41:47 AM CEST 
//


package iso.std.iso._20022.tech.xsd.scthr.pain_001_001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the iso.std.iso._20022.tech.xsd.scthr.pain_001_001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: iso.std.iso._20022.tech.xsd.scthr.pain_001_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice2 }
     * 
     */
    public AccountIdentification4Choice2 createAccountIdentification4Choice2() {
        return new AccountIdentification4Choice2();
    }

    /**
     * Create an instance of {@link CreditorReferenceType1Choice }
     * 
     */
    public CreditorReferenceType1Choice createCreditorReferenceType1Choice() {
        return new CreditorReferenceType1Choice();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     * 
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification18DbtrAgt }
     * 
     */
    public FinancialInstitutionIdentification18DbtrAgt createFinancialInstitutionIdentification18DbtrAgt() {
        return new FinancialInstitutionIdentification18DbtrAgt();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     * 
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification18CdtrAgt }
     * 
     */
    public FinancialInstitutionIdentification18CdtrAgt createFinancialInstitutionIdentification18CdtrAgt() {
        return new FinancialInstitutionIdentification18CdtrAgt();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link Party38Choice }
     * 
     */
    public Party38Choice createParty38Choice() {
        return new Party38Choice();
    }

    /**
     * Create an instance of {@link OrganisationIdentification29 }
     * 
     */
    public OrganisationIdentification29 createOrganisationIdentification29() {
        return new OrganisationIdentification29();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice }
     * 
     */
    public AccountIdentification4Choice createAccountIdentification4Choice() {
        return new AccountIdentification4Choice();
    }

    /**
     * Create an instance of {@link DateAndDateTime2Choice }
     * 
     */
    public DateAndDateTime2Choice createDateAndDateTime2Choice() {
        return new DateAndDateTime2Choice();
    }

    /**
     * Create an instance of {@link PartyIdentification1351 }
     * 
     */
    public PartyIdentification1351 createPartyIdentification1351() {
        return new PartyIdentification1351();
    }

    /**
     * Create an instance of {@link PartyIdentification1353 }
     * 
     */
    public PartyIdentification1353 createPartyIdentification1353() {
        return new PartyIdentification1353();
    }

    /**
     * Create an instance of {@link PartyIdentification1352 }
     * 
     */
    public PartyIdentification1352 createPartyIdentification1352() {
        return new PartyIdentification1352();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link Party38Choice1 }
     * 
     */
    public Party38Choice1 createParty38Choice1() {
        return new Party38Choice1();
    }

    /**
     * Create an instance of {@link PartyIdentification1354 }
     * 
     */
    public PartyIdentification1354 createPartyIdentification1354() {
        return new PartyIdentification1354();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth }
     * 
     */
    public DateAndPlaceOfBirth createDateAndPlaceOfBirth() {
        return new DateAndPlaceOfBirth();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation16 }
     * 
     */
    public StructuredRemittanceInformation16 createStructuredRemittanceInformation16() {
        return new StructuredRemittanceInformation16();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     * 
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice }
     * 
     */
    public CategoryPurpose1Choice createCategoryPurpose1Choice() {
        return new CategoryPurpose1Choice();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1 }
     * 
     */
    public GenericAccountIdentification1 createGenericAccountIdentification1() {
        return new GenericAccountIdentification1();
    }

    /**
     * Create an instance of {@link Purpose2Choice }
     * 
     */
    public Purpose2Choice createPurpose2Choice() {
        return new Purpose2Choice();
    }

    /**
     * Create an instance of {@link GroupHeader85 }
     * 
     */
    public GroupHeader85 createGroupHeader85() {
        return new GroupHeader85();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation26PmtInf }
     * 
     */
    public PaymentTypeInformation26PmtInf createPaymentTypeInformation26PmtInf() {
        return new PaymentTypeInformation26PmtInf();
    }

    /**
     * Create an instance of {@link RemittanceInformation16 }
     * 
     */
    public RemittanceInformation16 createRemittanceInformation16() {
        return new RemittanceInformation16();
    }

    /**
     * Create an instance of {@link ServiceLevel8Choice }
     * 
     */
    public ServiceLevel8Choice createServiceLevel8Choice() {
        return new ServiceLevel8Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceType2 }
     * 
     */
    public CreditorReferenceType2 createCreditorReferenceType2() {
        return new CreditorReferenceType2();
    }

    /**
     * Create an instance of {@link CashAccount38Cdtr }
     * 
     */
    public CashAccount38Cdtr createCashAccount38Cdtr() {
        return new CashAccount38Cdtr();
    }

    /**
     * Create an instance of {@link CustomerCreditTransferInitiationV09 }
     * 
     */
    public CustomerCreditTransferInitiationV09 createCustomerCreditTransferInitiationV09() {
        return new CustomerCreditTransferInitiationV09();
    }

    /**
     * Create an instance of {@link PostalAddress24 }
     * 
     */
    public PostalAddress24 createPostalAddress24() {
        return new PostalAddress24();
    }

    /**
     * Create an instance of {@link CreditTransferTransaction34 }
     * 
     */
    public CreditTransferTransaction34 createCreditTransferTransaction34() {
        return new CreditTransferTransaction34();
    }

    /**
     * Create an instance of {@link OrganisationIdentification291 }
     * 
     */
    public OrganisationIdentification291 createOrganisationIdentification291() {
        return new OrganisationIdentification291();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice }
     * 
     */
    public LocalInstrument2Choice createLocalInstrument2Choice() {
        return new LocalInstrument2Choice();
    }

    /**
     * Create an instance of {@link PersonIdentification13 }
     * 
     */
    public PersonIdentification13 createPersonIdentification13() {
        return new PersonIdentification13();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification6CdtrAgt }
     * 
     */
    public BranchAndFinancialInstitutionIdentification6CdtrAgt createBranchAndFinancialInstitutionIdentification6CdtrAgt() {
        return new BranchAndFinancialInstitutionIdentification6CdtrAgt();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification6DbtrAgt }
     * 
     */
    public BranchAndFinancialInstitutionIdentification6DbtrAgt createBranchAndFinancialInstitutionIdentification6DbtrAgt() {
        return new BranchAndFinancialInstitutionIdentification6DbtrAgt();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth1 }
     * 
     */
    public DateAndPlaceOfBirth1 createDateAndPlaceOfBirth1() {
        return new DateAndPlaceOfBirth1();
    }

    /**
     * Create an instance of {@link CashAccount38Dbtr }
     * 
     */
    public CashAccount38Dbtr createCashAccount38Dbtr() {
        return new CashAccount38Dbtr();
    }

    /**
     * Create an instance of {@link PaymentInstruction30 }
     * 
     */
    public PaymentInstruction30 createPaymentInstruction30() {
        return new PaymentInstruction30();
    }

    /**
     * Create an instance of {@link PaymentIdentification6 }
     * 
     */
    public PaymentIdentification6 createPaymentIdentification6() {
        return new PaymentIdentification6();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation26CdtTrfTxInf }
     * 
     */
    public PaymentTypeInformation26CdtTrfTxInf createPaymentTypeInformation26CdtTrfTxInf() {
        return new PaymentTypeInformation26CdtTrfTxInf();
    }

    /**
     * Create an instance of {@link AmountType4Choice }
     * 
     */
    public AmountType4Choice createAmountType4Choice() {
        return new AmountType4Choice();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation2 }
     * 
     */
    public CreditorReferenceInformation2 createCreditorReferenceInformation2() {
        return new CreditorReferenceInformation2();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.09", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
