//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.16 at 12:12:18 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.temeljnitipovi.v2_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tJezik.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tJezik">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="hr-HR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tJezik", namespace = "http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1")
@XmlEnum
public enum TJezik {

    @XmlEnumValue("hr-HR")
    HR_HR("hr-HR");
    private final String value;

    TJezik(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TJezik fromValue(String v) {
        for (TJezik c: TJezik.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
