//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.21 at 11:12:14 AM CET 
//


package hr.porezna_uprava.e_porezna.sheme.temeljnitipovi.v2_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tTip.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tTip">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Elektroni?ki obrazac"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tTip", namespace = "http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1")
@XmlEnum
public enum TTip {

    @XmlEnumValue("Elektroni\u010dki obrazac")
    ELEKTRONIČKI_OBRAZAC("Elektroni\u010dki obrazac");
    private final String value;

    TTip(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TTip fromValue(String v) {
        for (TTip c: TTip.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
