//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.27 at 12:36:28 PM CEST 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacpdvs.v1_0;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Isporuka, sadrži podatke o vrijednostima isporuka od jednog isporučitelja
 * 
 * <p>Java class for sIsporuka complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sIsporuka">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RedBr" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="KodDrzave" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDVS/v1-0}tKodDrzave"/>
 *         &lt;element name="PDVID" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDVS/v1-0}tPDVID"/>
 *         &lt;element name="I1" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="I2" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sIsporuka", propOrder = {
    "redBr",
    "kodDrzave",
    "pdvid",
    "i1",
    "i2"
})
public class SIsporuka {

    @XmlElement(name = "RedBr", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger redBr;
    @XmlElement(name = "KodDrzave", required = true)
    protected TKodDrzave kodDrzave;
    @XmlElement(name = "PDVID", required = true)
    protected String pdvid;
    @XmlElement(name = "I1", required = true)
    protected BigDecimal i1;
    @XmlElement(name = "I2", required = true)
    protected BigDecimal i2;

    /**
     * Gets the value of the redBr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRedBr() {
        return redBr;
    }

    /**
     * Sets the value of the redBr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRedBr(BigInteger value) {
        this.redBr = value;
    }

    /**
     * Gets the value of the kodDrzave property.
     * 
     * @return
     *     possible object is
     *     {@link TKodDrzave }
     *     
     */
    public TKodDrzave getKodDrzave() {
        return kodDrzave;
    }

    /**
     * Sets the value of the kodDrzave property.
     * 
     * @param value
     *     allowed object is
     *     {@link TKodDrzave }
     *     
     */
    public void setKodDrzave(TKodDrzave value) {
        this.kodDrzave = value;
    }

    /**
     * Gets the value of the pdvid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDVID() {
        return pdvid;
    }

    /**
     * Sets the value of the pdvid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDVID(String value) {
        this.pdvid = value;
    }

    /**
     * Gets the value of the i1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getI1() {
        return i1;
    }

    /**
     * Sets the value of the i1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setI1(BigDecimal value) {
        this.i1 = value;
    }

    /**
     * Gets the value of the i2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getI2() {
        return i2;
    }

    /**
     * Sets the value of the i2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setI2(BigDecimal value) {
        this.i2 = value;
    }

}
