//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.08 at 10:19:02 AM CEST 
//


package hr.fina.eracun.b2g.pki.echo.v0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import hr.fina.eracun.b2g.invoicewebservicecomponents.v0.MessageAckType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1}MessageAck"/>
 *         &lt;element name="EchoData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Echo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageAck",
    "echoData"
})
@XmlRootElement(name = "EchoAckMsg")
public class EchoAckMsg {

    @XmlElement(name = "MessageAck", namespace = "http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", required = true)
    protected MessageAckType messageAck;
    @XmlElement(name = "EchoData", required = true)
    protected EchoAckMsg.EchoData echoData;

    /**
     * Gets the value of the messageAck property.
     * 
     * @return
     *     possible object is
     *     {@link MessageAckType }
     *     
     */
    public MessageAckType getMessageAck() {
        return messageAck;
    }

    /**
     * Sets the value of the messageAck property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageAckType }
     *     
     */
    public void setMessageAck(MessageAckType value) {
        this.messageAck = value;
    }

    /**
     * Gets the value of the echoData property.
     * 
     * @return
     *     possible object is
     *     {@link EchoAckMsg.EchoData }
     *     
     */
    public EchoAckMsg.EchoData getEchoData() {
        return echoData;
    }

    /**
     * Sets the value of the echoData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EchoAckMsg.EchoData }
     *     
     */
    public void setEchoData(EchoAckMsg.EchoData value) {
        this.echoData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Echo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "echo"
    })
    public static class EchoData {

        @XmlElement(name = "Echo", required = true)
        protected String echo;

        /**
         * Gets the value of the echo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEcho() {
            return echo;
        }

        /**
         * Sets the value of the echo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEcho(String value) {
            this.echo = value;
        }

    }

}
