//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.08 at 10:19:02 AM CEST 
//


package hr.fina.eracun.b2g.pki.echo.v0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.fina.eracun.b2g.pki.echo.v0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.fina.eracun.b2g.pki.echo.v0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EchoMsg }
     * 
     */
    public EchoMsg createEchoMsg() {
        return new EchoMsg();
    }

    /**
     * Create an instance of {@link EchoAckMsg }
     * 
     */
    public EchoAckMsg createEchoAckMsg() {
        return new EchoAckMsg();
    }

    /**
     * Create an instance of {@link EchoMsg.Data }
     * 
     */
    public EchoMsg.Data createEchoMsgData() {
        return new EchoMsg.Data();
    }

    /**
     * Create an instance of {@link EchoAckMsg.EchoData }
     * 
     */
    public EchoAckMsg.EchoData createEchoAckMsgEchoData() {
        return new EchoAckMsg.EchoData();
    }

    /**
     * Create an instance of {@link EchoMsg.Data.EchoData }
     * 
     */
    public EchoMsg.Data.EchoData createEchoMsgDataEchoData() {
        return new EchoMsg.Data.EchoData();
    }

}
