//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.11 at 12:23:25 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacopz.v1_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tijelo obrasca
 * 
 * <p>Java class for sTijelo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sTijelo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Kupci" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacOPZ/v1-0}sKupci"/>
 *         &lt;element name="UkupanIznosRacunaObrasca" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *         &lt;element name="UkupanIznosPdvObrasca" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *         &lt;element name="UkupanIznosRacunaSPdvObrasca" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *         &lt;element name="UkupniPlaceniIznosRacunaObrasca" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *         &lt;element name="NeplaceniIznosRacunaObrasca" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *         &lt;element name="OPZUkupanIznosRacunaSPdv" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *         &lt;element name="OPZUkupanIznosPdv" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tNonNegativeDecimal15-2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sTijelo", propOrder = {
    "kupci",
    "ukupanIznosRacunaObrasca",
    "ukupanIznosPdvObrasca",
    "ukupanIznosRacunaSPdvObrasca",
    "ukupniPlaceniIznosRacunaObrasca",
    "neplaceniIznosRacunaObrasca",
    "opzUkupanIznosRacunaSPdv",
    "opzUkupanIznosPdv"
})
public class STijelo {

    @XmlElement(name = "Kupci", required = true)
    protected SKupci kupci;
    @XmlElement(name = "UkupanIznosRacunaObrasca", required = true)
    protected BigDecimal ukupanIznosRacunaObrasca;
    @XmlElement(name = "UkupanIznosPdvObrasca", required = true)
    protected BigDecimal ukupanIznosPdvObrasca;
    @XmlElement(name = "UkupanIznosRacunaSPdvObrasca", required = true)
    protected BigDecimal ukupanIznosRacunaSPdvObrasca;
    @XmlElement(name = "UkupniPlaceniIznosRacunaObrasca", required = true)
    protected BigDecimal ukupniPlaceniIznosRacunaObrasca;
    @XmlElement(name = "NeplaceniIznosRacunaObrasca", required = true)
    protected BigDecimal neplaceniIznosRacunaObrasca;
    @XmlElement(name = "OPZUkupanIznosRacunaSPdv", required = true)
    protected BigDecimal opzUkupanIznosRacunaSPdv;
    @XmlElement(name = "OPZUkupanIznosPdv", required = true)
    protected BigDecimal opzUkupanIznosPdv;

    /**
     * Gets the value of the kupci property.
     * 
     * @return
     *     possible object is
     *     {@link SKupci }
     *     
     */
    public SKupci getKupci() {
        return kupci;
    }

    /**
     * Sets the value of the kupci property.
     * 
     * @param value
     *     allowed object is
     *     {@link SKupci }
     *     
     */
    public void setKupci(SKupci value) {
        this.kupci = value;
    }

    /**
     * Gets the value of the ukupanIznosRacunaObrasca property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupanIznosRacunaObrasca() {
        return ukupanIznosRacunaObrasca;
    }

    /**
     * Sets the value of the ukupanIznosRacunaObrasca property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupanIznosRacunaObrasca(BigDecimal value) {
        this.ukupanIznosRacunaObrasca = value;
    }

    /**
     * Gets the value of the ukupanIznosPdvObrasca property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupanIznosPdvObrasca() {
        return ukupanIznosPdvObrasca;
    }

    /**
     * Sets the value of the ukupanIznosPdvObrasca property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupanIznosPdvObrasca(BigDecimal value) {
        this.ukupanIznosPdvObrasca = value;
    }

    /**
     * Gets the value of the ukupanIznosRacunaSPdvObrasca property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupanIznosRacunaSPdvObrasca() {
        return ukupanIznosRacunaSPdvObrasca;
    }

    /**
     * Sets the value of the ukupanIznosRacunaSPdvObrasca property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupanIznosRacunaSPdvObrasca(BigDecimal value) {
        this.ukupanIznosRacunaSPdvObrasca = value;
    }

    /**
     * Gets the value of the ukupniPlaceniIznosRacunaObrasca property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupniPlaceniIznosRacunaObrasca() {
        return ukupniPlaceniIznosRacunaObrasca;
    }

    /**
     * Sets the value of the ukupniPlaceniIznosRacunaObrasca property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupniPlaceniIznosRacunaObrasca(BigDecimal value) {
        this.ukupniPlaceniIznosRacunaObrasca = value;
    }

    /**
     * Gets the value of the neplaceniIznosRacunaObrasca property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNeplaceniIznosRacunaObrasca() {
        return neplaceniIznosRacunaObrasca;
    }

    /**
     * Sets the value of the neplaceniIznosRacunaObrasca property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNeplaceniIznosRacunaObrasca(BigDecimal value) {
        this.neplaceniIznosRacunaObrasca = value;
    }

    /**
     * Gets the value of the opzUkupanIznosRacunaSPdv property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOPZUkupanIznosRacunaSPdv() {
        return opzUkupanIznosRacunaSPdv;
    }

    /**
     * Sets the value of the opzUkupanIznosRacunaSPdv property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOPZUkupanIznosRacunaSPdv(BigDecimal value) {
        this.opzUkupanIznosRacunaSPdv = value;
    }

    /**
     * Gets the value of the opzUkupanIznosPdv property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOPZUkupanIznosPdv() {
        return opzUkupanIznosPdv;
    }

    /**
     * Sets the value of the opzUkupanIznosPdv property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOPZUkupanIznosPdv(BigDecimal value) {
        this.opzUkupanIznosPdv = value;
    }

}
