//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.11 at 09:21:43 AM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacopz.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Zaglavlje obrasca
 * 
 * <p>Java class for sZaglavlje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sZaglavlje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Razdoblje" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacOPZ/v1-0}sRazdoblje"/>
 *         &lt;element name="PorezniObveznik" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacOPZ/v1-0}sPorezniObveznik"/>
 *         &lt;element name="IzvjesceSastavio" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacOPZ/v1-0}sIzvjesceSastavio"/>
 *         &lt;element name="NaDan" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="NisuNaplaceniDo" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sZaglavlje", propOrder = {
    "razdoblje",
    "porezniObveznik",
    "izvjesceSastavio",
    "naDan",
    "nisuNaplaceniDo"
})
public class SZaglavlje {

    @XmlElement(name = "Razdoblje", required = true)
    protected SRazdoblje razdoblje;
    @XmlElement(name = "PorezniObveznik", required = true)
    protected SPorezniObveznik porezniObveznik;
    @XmlElement(name = "IzvjesceSastavio", required = true)
    protected SIzvjesceSastavio izvjesceSastavio;
    @XmlElement(name = "NaDan", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar naDan;
    @XmlElement(name = "NisuNaplaceniDo", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar nisuNaplaceniDo;

    /**
     * Gets the value of the razdoblje property.
     * 
     * @return
     *     possible object is
     *     {@link SRazdoblje }
     *     
     */
    public SRazdoblje getRazdoblje() {
        return razdoblje;
    }

    /**
     * Sets the value of the razdoblje property.
     * 
     * @param value
     *     allowed object is
     *     {@link SRazdoblje }
     *     
     */
    public void setRazdoblje(SRazdoblje value) {
        this.razdoblje = value;
    }

    /**
     * Gets the value of the porezniObveznik property.
     * 
     * @return
     *     possible object is
     *     {@link SPorezniObveznik }
     *     
     */
    public SPorezniObveznik getPorezniObveznik() {
        return porezniObveznik;
    }

    /**
     * Sets the value of the porezniObveznik property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPorezniObveznik }
     *     
     */
    public void setPorezniObveznik(SPorezniObveznik value) {
        this.porezniObveznik = value;
    }

    /**
     * Gets the value of the izvjesceSastavio property.
     * 
     * @return
     *     possible object is
     *     {@link SIzvjesceSastavio }
     *     
     */
    public SIzvjesceSastavio getIzvjesceSastavio() {
        return izvjesceSastavio;
    }

    /**
     * Sets the value of the izvjesceSastavio property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIzvjesceSastavio }
     *     
     */
    public void setIzvjesceSastavio(SIzvjesceSastavio value) {
        this.izvjesceSastavio = value;
    }

    /**
     * Gets the value of the naDan property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNaDan() {
        return naDan;
    }

    /**
     * Sets the value of the naDan property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNaDan(XMLGregorianCalendar value) {
        this.naDan = value;
    }

    /**
     * Gets the value of the nisuNaplaceniDo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNisuNaplaceniDo() {
        return nisuNaplaceniDo;
    }

    /**
     * Sets the value of the nisuNaplaceniDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNisuNaplaceniDo(XMLGregorianCalendar value) {
        this.nisuNaplaceniDo = value;
    }

}
