//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.15 at 10:49:26 AM CEST 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacjoppd.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Strana B
 * 
 * <p>Java class for sStranaB complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sStranaB">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Primatelji" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacJOPPD/v1-0}sPrimatelji" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sStranaB", propOrder = {
    "primatelji"
})
public class SStranaB {

    @XmlElement(name = "Primatelji", required = true)
    protected List<SPrimatelji> primatelji;

    /**
     * Gets the value of the primatelji property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the primatelji property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrimatelji().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SPrimatelji }
     * 
     * 
     */
    public List<SPrimatelji> getPrimatelji() {
        if (primatelji == null) {
            primatelji = new ArrayList<SPrimatelji>();
        }
        return this.primatelji;
    }

}
