//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.16 at 12:12:18 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacid.v3_0;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * III. OBRA?UNANI DOPRINOSI UKUPNO
 * 
 * <p>Java class for sDoprinosiUkupno complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sDoprinosiUkupno">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Podatak110" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
 *         &lt;element name="Podatak120" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
 *         &lt;element name="Podatak210" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
 *         &lt;element name="Podatak220" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
 *         &lt;element name="Podatak310" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
 *         &lt;element name="Podatak320" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
 *         &lt;element name="Podatak330" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
 *         &lt;element name="Podatak410" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
 *         &lt;element name="Podatak420" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
 *         &lt;element name="Podatak500" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sDoprinosiUkupno", propOrder = {
    "podatak110",
    "podatak120",
    "podatak210",
    "podatak220",
    "podatak310",
    "podatak320",
    "podatak330",
    "podatak410",
    "podatak420",
    "podatak500"
})
public class SDoprinosiUkupno {

    @XmlElement(name = "Podatak110", required = true)
    protected BigDecimal podatak110;
    @XmlElement(name = "Podatak120", required = true)
    protected BigDecimal podatak120;
    @XmlElement(name = "Podatak210", required = true)
    protected BigDecimal podatak210;
    @XmlElement(name = "Podatak220", required = true)
    protected BigDecimal podatak220;
    @XmlElement(name = "Podatak310", required = true)
    protected BigDecimal podatak310;
    @XmlElement(name = "Podatak320", required = true)
    protected BigDecimal podatak320;
    @XmlElement(name = "Podatak330", required = true)
    protected BigDecimal podatak330;
    @XmlElement(name = "Podatak410", required = true)
    protected BigDecimal podatak410;
    @XmlElement(name = "Podatak420", required = true)
    protected BigDecimal podatak420;
    @XmlElement(name = "Podatak500", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger podatak500;

    /**
     * Gets the value of the podatak110 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak110() {
        return podatak110;
    }

    /**
     * Sets the value of the podatak110 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak110(BigDecimal value) {
        this.podatak110 = value;
    }

    /**
     * Gets the value of the podatak120 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak120() {
        return podatak120;
    }

    /**
     * Sets the value of the podatak120 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak120(BigDecimal value) {
        this.podatak120 = value;
    }

    /**
     * Gets the value of the podatak210 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak210() {
        return podatak210;
    }

    /**
     * Sets the value of the podatak210 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak210(BigDecimal value) {
        this.podatak210 = value;
    }

    /**
     * Gets the value of the podatak220 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak220() {
        return podatak220;
    }

    /**
     * Sets the value of the podatak220 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak220(BigDecimal value) {
        this.podatak220 = value;
    }

    /**
     * Gets the value of the podatak310 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak310() {
        return podatak310;
    }

    /**
     * Sets the value of the podatak310 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak310(BigDecimal value) {
        this.podatak310 = value;
    }

    /**
     * Gets the value of the podatak320 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak320() {
        return podatak320;
    }

    /**
     * Sets the value of the podatak320 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak320(BigDecimal value) {
        this.podatak320 = value;
    }

    /**
     * Gets the value of the podatak330 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak330() {
        return podatak330;
    }

    /**
     * Sets the value of the podatak330 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak330(BigDecimal value) {
        this.podatak330 = value;
    }

    /**
     * Gets the value of the podatak410 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak410() {
        return podatak410;
    }

    /**
     * Sets the value of the podatak410 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak410(BigDecimal value) {
        this.podatak410 = value;
    }

    /**
     * Gets the value of the podatak420 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPodatak420() {
        return podatak420;
    }

    /**
     * Sets the value of the podatak420 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPodatak420(BigDecimal value) {
        this.podatak420 = value;
    }

    /**
     * Gets the value of the podatak500 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPodatak500() {
        return podatak500;
    }

    /**
     * Sets the value of the podatak500 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPodatak500(BigInteger value) {
        this.podatak500 = value;
    }

}
