//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.16 at 12:12:18 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacid.v3_0;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * IV. Podaci o obra?unanom porezu i prirezu prema op?ini/gradu
 * 
 * <p>Java class for sPorezIprirezPremaOpciniGradu complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sPorezIprirezPremaOpciniGradu">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ObracunatiPorez" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Sifra">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="[0-9]{3}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Poreza" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
 *                   &lt;element name="Prireza" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
 *                   &lt;element name="Ukupno" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sPorezIprirezPremaOpciniGradu", propOrder = {
    "obracunatiPorez"
})
public class SPorezIprirezPremaOpciniGradu {

    @XmlElement(name = "ObracunatiPorez")
    protected List<SPorezIprirezPremaOpciniGradu.ObracunatiPorez> obracunatiPorez;

    /**
     * Gets the value of the obracunatiPorez property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the obracunatiPorez property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObracunatiPorez().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SPorezIprirezPremaOpciniGradu.ObracunatiPorez }
     * 
     * 
     */
    public List<SPorezIprirezPremaOpciniGradu.ObracunatiPorez> getObracunatiPorez() {
        if (obracunatiPorez == null) {
            obracunatiPorez = new ArrayList<SPorezIprirezPremaOpciniGradu.ObracunatiPorez>();
        }
        return this.obracunatiPorez;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Sifra">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="[0-9]{3}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Poreza" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
     *         &lt;element name="Prireza" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
     *         &lt;element name="Ukupno" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal14-2"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sifra",
        "poreza",
        "prireza",
        "ukupno"
    })
    public static class ObracunatiPorez {

        @XmlElement(name = "Sifra", required = true)
        protected String sifra;
        @XmlElement(name = "Poreza", required = true)
        protected BigDecimal poreza;
        @XmlElement(name = "Prireza", required = true)
        protected BigDecimal prireza;
        @XmlElement(name = "Ukupno", required = true)
        protected BigDecimal ukupno;

        /**
         * Gets the value of the sifra property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSifra() {
            return sifra;
        }

        /**
         * Sets the value of the sifra property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSifra(String value) {
            this.sifra = value;
        }

        /**
         * Gets the value of the poreza property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPoreza() {
            return poreza;
        }

        /**
         * Sets the value of the poreza property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPoreza(BigDecimal value) {
            this.poreza = value;
        }

        /**
         * Gets the value of the prireza property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPrireza() {
            return prireza;
        }

        /**
         * Sets the value of the prireza property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPrireza(BigDecimal value) {
            this.prireza = value;
        }

        /**
         * Gets the value of the ukupno property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getUkupno() {
            return ukupno;
        }

        /**
         * Sets the value of the ukupno property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setUkupno(BigDecimal value) {
            this.ukupno = value;
        }

    }

}
