//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.16 at 12:12:18 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacid.v3_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Zaglavlje obrasca
 * 
 * <p>Java class for sZaglavlje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sZaglavlje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PodrucniUred" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOgraniceniZnakovniNizMin2Max128"/>
 *         &lt;element name="Ispostava" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tIspostava"/>
 *         &lt;element name="Razdoblje" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacID/v3-0}sRazdoblje"/>
 *         &lt;element name="PodnositeljZahtjeva">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacID/v3-0}sPoslovniSubjekt">
 *                 &lt;sequence>
 *                   &lt;element name="Adresa" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacID/v3-0}sAdresa"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Identifikator" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacID/v3-0}sIdentifikator"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sZaglavlje", propOrder = {
    "podrucniUred",
    "ispostava",
    "razdoblje",
    "podnositeljZahtjeva",
    "identifikator"
})
public class SZaglavlje {

    @XmlElement(name = "PodrucniUred", required = true)
    protected String podrucniUred;
    @XmlElement(name = "Ispostava", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ispostava;
    @XmlElement(name = "Razdoblje", required = true)
    protected SRazdoblje razdoblje;
    @XmlElement(name = "PodnositeljZahtjeva", required = true)
    protected SZaglavlje.PodnositeljZahtjeva podnositeljZahtjeva;
    @XmlElement(name = "Identifikator", required = true)
    protected String identifikator;

    /**
     * Gets the value of the podrucniUred property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPodrucniUred() {
        return podrucniUred;
    }

    /**
     * Sets the value of the podrucniUred property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPodrucniUred(String value) {
        this.podrucniUred = value;
    }

    /**
     * Gets the value of the ispostava property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIspostava() {
        return ispostava;
    }

    /**
     * Sets the value of the ispostava property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIspostava(String value) {
        this.ispostava = value;
    }

    /**
     * Gets the value of the razdoblje property.
     * 
     * @return
     *     possible object is
     *     {@link SRazdoblje }
     *     
     */
    public SRazdoblje getRazdoblje() {
        return razdoblje;
    }

    /**
     * Sets the value of the razdoblje property.
     * 
     * @param value
     *     allowed object is
     *     {@link SRazdoblje }
     *     
     */
    public void setRazdoblje(SRazdoblje value) {
        this.razdoblje = value;
    }

    /**
     * Gets the value of the podnositeljZahtjeva property.
     * 
     * @return
     *     possible object is
     *     {@link SZaglavlje.PodnositeljZahtjeva }
     *     
     */
    public SZaglavlje.PodnositeljZahtjeva getPodnositeljZahtjeva() {
        return podnositeljZahtjeva;
    }

    /**
     * Sets the value of the podnositeljZahtjeva property.
     * 
     * @param value
     *     allowed object is
     *     {@link SZaglavlje.PodnositeljZahtjeva }
     *     
     */
    public void setPodnositeljZahtjeva(SZaglavlje.PodnositeljZahtjeva value) {
        this.podnositeljZahtjeva = value;
    }

    /**
     * Gets the value of the identifikator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifikator() {
        return identifikator;
    }

    /**
     * Sets the value of the identifikator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifikator(String value) {
        this.identifikator = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacID/v3-0}sPoslovniSubjekt">
     *       &lt;sequence>
     *         &lt;element name="Adresa" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacID/v3-0}sAdresa"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "adresa"
    })
    public static class PodnositeljZahtjeva
        extends SPoslovniSubjekt
    {

        @XmlElement(name = "Adresa", required = true)
        protected SAdresa adresa;

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link SAdresa }
         *     
         */
        public SAdresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link SAdresa }
         *     
         */
        public void setAdresa(SAdresa value) {
            this.adresa = value;
        }

    }

}
