//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.12 at 01:49:31 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacura.v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacura.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ObrazacURA_QNAME = new QName("http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v1-0", "ObrazacURA");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacura.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SObrazacURA }
     * 
     */
    public SObrazacURA createSObrazacURA() {
        return new SObrazacURA();
    }

    /**
     * Create an instance of {@link SZaglavlje }
     * 
     */
    public SZaglavlje createSZaglavlje() {
        return new SZaglavlje();
    }

    /**
     * Create an instance of {@link SIspunjavatelj }
     * 
     */
    public SIspunjavatelj createSIspunjavatelj() {
        return new SIspunjavatelj();
    }

    /**
     * Create an instance of {@link SRazdoblje }
     * 
     */
    public SRazdoblje createSRazdoblje() {
        return new SRazdoblje();
    }

    /**
     * Create an instance of {@link SPoslovniSubjekt }
     * 
     */
    public SPoslovniSubjekt createSPoslovniSubjekt() {
        return new SPoslovniSubjekt();
    }

    /**
     * Create an instance of {@link SRacuniUkupno }
     * 
     */
    public SRacuniUkupno createSRacuniUkupno() {
        return new SRacuniUkupno();
    }

    /**
     * Create an instance of {@link SRacuniList }
     * 
     */
    public SRacuniList createSRacuniList() {
        return new SRacuniList();
    }

    /**
     * Create an instance of {@link SRacun }
     * 
     */
    public SRacun createSRacun() {
        return new SRacun();
    }

    /**
     * Create an instance of {@link SAdresa }
     * 
     */
    public SAdresa createSAdresa() {
        return new SAdresa();
    }

    /**
     * Create an instance of {@link SPorezniObveznik }
     * 
     */
    public SPorezniObveznik createSPorezniObveznik() {
        return new SPorezniObveznik();
    }

    /**
     * Create an instance of {@link STijelo }
     * 
     */
    public STijelo createSTijelo() {
        return new STijelo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SObrazacURA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v1-0", name = "ObrazacURA")
    public JAXBElement<SObrazacURA> createObrazacURA(SObrazacURA value) {
        return new JAXBElement<SObrazacURA>(_ObrazacURA_QNAME, SObrazacURA.class, null, value);
    }

}
