//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.12 at 01:49:31 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacura.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sIspunjavatelj complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sIspunjavatelj">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Ime" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOgraniceniZnakovniNizMin2Max128"/>
 *         &lt;element name="Prezime" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOgraniceniZnakovniNizMin2Max128"/>
 *         &lt;element name="PoslovniSubjekt" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v1-0}sPoslovniSubjekt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sIspunjavatelj", propOrder = {
    "ime",
    "prezime",
    "poslovniSubjekt"
})
public class SIspunjavatelj {

    @XmlElement(name = "Ime", required = true)
    protected String ime;
    @XmlElement(name = "Prezime", required = true)
    protected String prezime;
    @XmlElement(name = "PoslovniSubjekt")
    protected SPoslovniSubjekt poslovniSubjekt;

    /**
     * Gets the value of the ime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIme() {
        return ime;
    }

    /**
     * Sets the value of the ime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIme(String value) {
        this.ime = value;
    }

    /**
     * Gets the value of the prezime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrezime() {
        return prezime;
    }

    /**
     * Sets the value of the prezime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrezime(String value) {
        this.prezime = value;
    }

    /**
     * Gets the value of the poslovniSubjekt property.
     * 
     * @return
     *     possible object is
     *     {@link SPoslovniSubjekt }
     *     
     */
    public SPoslovniSubjekt getPoslovniSubjekt() {
        return poslovniSubjekt;
    }

    /**
     * Sets the value of the poslovniSubjekt property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPoslovniSubjekt }
     *     
     */
    public void setPoslovniSubjekt(SPoslovniSubjekt value) {
        this.poslovniSubjekt = value;
    }

}
