//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.12 at 01:49:31 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacura.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sPorezniObveznik complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sPorezniObveznik">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="OIB" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOIB"/>
 *           &lt;element name="PDVID" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOIB"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="Naziv" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOgraniceniZnakovniNizMin2Max128"/>
 *           &lt;sequence>
 *             &lt;element name="Ime" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOgraniceniZnakovniNizMin2Max128"/>
 *             &lt;element name="Prezime" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOgraniceniZnakovniNizMin2Max128"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="Adresa" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v1-0}sAdresa"/>
 *         &lt;element name="PodrucjeDjelatnosti" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v1-0}tPodrucjeDjelatnosti"/>
 *         &lt;element name="SifraDjelatnosti" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tSifraDjelatnosti"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sPorezniObveznik", propOrder = {
    "oib",
    "pdvid",
    "naziv",
    "ime",
    "prezime",
    "adresa",
    "podrucjeDjelatnosti",
    "sifraDjelatnosti"
})
public class SPorezniObveznik {

    @XmlElement(name = "OIB")
    protected String oib;
    @XmlElement(name = "PDVID")
    protected String pdvid;
    @XmlElement(name = "Naziv")
    protected String naziv;
    @XmlElement(name = "Ime")
    protected String ime;
    @XmlElement(name = "Prezime")
    protected String prezime;
    @XmlElement(name = "Adresa", required = true)
    protected SAdresa adresa;
    @XmlElement(name = "PodrucjeDjelatnosti", required = true)
    protected String podrucjeDjelatnosti;
    @XmlElement(name = "SifraDjelatnosti", required = true)
    protected String sifraDjelatnosti;

    /**
     * Gets the value of the oib property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOIB() {
        return oib;
    }

    /**
     * Sets the value of the oib property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOIB(String value) {
        this.oib = value;
    }

    /**
     * Gets the value of the pdvid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPDVID() {
        return pdvid;
    }

    /**
     * Sets the value of the pdvid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPDVID(String value) {
        this.pdvid = value;
    }

    /**
     * Gets the value of the naziv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaziv() {
        return naziv;
    }

    /**
     * Sets the value of the naziv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaziv(String value) {
        this.naziv = value;
    }

    /**
     * Gets the value of the ime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIme() {
        return ime;
    }

    /**
     * Sets the value of the ime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIme(String value) {
        this.ime = value;
    }

    /**
     * Gets the value of the prezime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrezime() {
        return prezime;
    }

    /**
     * Sets the value of the prezime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrezime(String value) {
        this.prezime = value;
    }

    /**
     * Gets the value of the adresa property.
     * 
     * @return
     *     possible object is
     *     {@link SAdresa }
     *     
     */
    public SAdresa getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link SAdresa }
     *     
     */
    public void setAdresa(SAdresa value) {
        this.adresa = value;
    }

    /**
     * Gets the value of the podrucjeDjelatnosti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPodrucjeDjelatnosti() {
        return podrucjeDjelatnosti;
    }

    /**
     * Sets the value of the podrucjeDjelatnosti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPodrucjeDjelatnosti(String value) {
        this.podrucjeDjelatnosti = value;
    }

    /**
     * Gets the value of the sifraDjelatnosti property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifraDjelatnosti() {
        return sifraDjelatnosti;
    }

    /**
     * Sets the value of the sifraDjelatnosti property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifraDjelatnosti(String value) {
        this.sifraDjelatnosti = value;
    }

}
