//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.12 at 01:49:31 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacura.v1_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for sRacun complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sRacun">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="R1">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *               &lt;minInclusive value="1"/>
 *               &lt;maxInclusive value="9999999999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="R2">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="64"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="R3" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="R4" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v1-0}tOgraniceniZnakovniNizMin0Max128"/>
 *         &lt;element name="R5" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v1-0}tOgraniceniZnakovniNizMin0Max200"/>
 *         &lt;element name="R6" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v1-0}tTipIdBroja"/>
 *         &lt;element name="R7" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tOIB"/>
 *         &lt;element name="R8" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="R9" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="R10" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="R11" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="R12" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="R13" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="R14" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="R15" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="R16" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="R17" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="R18" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sRacun", propOrder = {
    "r1",
    "r2",
    "r3",
    "r4",
    "r5",
    "r6",
    "r7",
    "r8",
    "r9",
    "r10",
    "r11",
    "r12",
    "r13",
    "r14",
    "r15",
    "r16",
    "r17",
    "r18"
})
public class SRacun {

    @XmlElement(name = "R1")
    protected long r1;
    @XmlElement(name = "R2", required = true)
    protected String r2;
    @XmlElement(name = "R3", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar r3;
    @XmlElement(name = "R4", required = true)
    protected String r4;
    @XmlElement(name = "R5", required = true)
    protected String r5;
    @XmlElement(name = "R6")
    protected int r6;
    @XmlElement(name = "R7", required = true)
    protected String r7;
    @XmlElement(name = "R8", required = true)
    protected BigDecimal r8;
    @XmlElement(name = "R9", required = true)
    protected BigDecimal r9;
    @XmlElement(name = "R10", required = true)
    protected BigDecimal r10;
    @XmlElement(name = "R11", required = true)
    protected BigDecimal r11;
    @XmlElement(name = "R12", required = true)
    protected BigDecimal r12;
    @XmlElement(name = "R13", required = true)
    protected BigDecimal r13;
    @XmlElement(name = "R14", required = true)
    protected BigDecimal r14;
    @XmlElement(name = "R15", required = true)
    protected BigDecimal r15;
    @XmlElement(name = "R16", required = true)
    protected BigDecimal r16;
    @XmlElement(name = "R17", required = true)
    protected BigDecimal r17;
    @XmlElement(name = "R18", required = true)
    protected BigDecimal r18;

    /**
     * Gets the value of the r1 property.
     * 
     */
    public long getR1() {
        return r1;
    }

    /**
     * Sets the value of the r1 property.
     * 
     */
    public void setR1(long value) {
        this.r1 = value;
    }

    /**
     * Gets the value of the r2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getR2() {
        return r2;
    }

    /**
     * Sets the value of the r2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setR2(String value) {
        this.r2 = value;
    }

    /**
     * Gets the value of the r3 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getR3() {
        return r3;
    }

    /**
     * Sets the value of the r3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setR3(XMLGregorianCalendar value) {
        this.r3 = value;
    }

    /**
     * Gets the value of the r4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getR4() {
        return r4;
    }

    /**
     * Sets the value of the r4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setR4(String value) {
        this.r4 = value;
    }

    /**
     * Gets the value of the r5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getR5() {
        return r5;
    }

    /**
     * Sets the value of the r5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setR5(String value) {
        this.r5 = value;
    }

    /**
     * Gets the value of the r6 property.
     * 
     */
    public int getR6() {
        return r6;
    }

    /**
     * Sets the value of the r6 property.
     * 
     */
    public void setR6(int value) {
        this.r6 = value;
    }

    /**
     * Gets the value of the r7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getR7() {
        return r7;
    }

    /**
     * Sets the value of the r7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setR7(String value) {
        this.r7 = value;
    }

    /**
     * Gets the value of the r8 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getR8() {
        return r8;
    }

    /**
     * Sets the value of the r8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setR8(BigDecimal value) {
        this.r8 = value;
    }

    /**
     * Gets the value of the r9 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getR9() {
        return r9;
    }

    /**
     * Sets the value of the r9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setR9(BigDecimal value) {
        this.r9 = value;
    }

    /**
     * Gets the value of the r10 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getR10() {
        return r10;
    }

    /**
     * Sets the value of the r10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setR10(BigDecimal value) {
        this.r10 = value;
    }

    /**
     * Gets the value of the r11 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getR11() {
        return r11;
    }

    /**
     * Sets the value of the r11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setR11(BigDecimal value) {
        this.r11 = value;
    }

    /**
     * Gets the value of the r12 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getR12() {
        return r12;
    }

    /**
     * Sets the value of the r12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setR12(BigDecimal value) {
        this.r12 = value;
    }

    /**
     * Gets the value of the r13 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getR13() {
        return r13;
    }

    /**
     * Sets the value of the r13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setR13(BigDecimal value) {
        this.r13 = value;
    }

    /**
     * Gets the value of the r14 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getR14() {
        return r14;
    }

    /**
     * Sets the value of the r14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setR14(BigDecimal value) {
        this.r14 = value;
    }

    /**
     * Gets the value of the r15 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getR15() {
        return r15;
    }

    /**
     * Sets the value of the r15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setR15(BigDecimal value) {
        this.r15 = value;
    }

    /**
     * Gets the value of the r16 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getR16() {
        return r16;
    }

    /**
     * Sets the value of the r16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setR16(BigDecimal value) {
        this.r16 = value;
    }

    /**
     * Gets the value of the r17 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getR17() {
        return r17;
    }

    /**
     * Sets the value of the r17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setR17(BigDecimal value) {
        this.r17 = value;
    }

    /**
     * Gets the value of the r18 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getR18() {
        return r18;
    }

    /**
     * Sets the value of the r18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setR18(BigDecimal value) {
        this.r18 = value;
    }

}
