//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.12 at 01:49:31 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacura.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tijelo obrasca
 * 
 * <p>Java class for sTijelo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sTijelo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Racuni" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v1-0}sRacuniList"/>
 *         &lt;element name="Ukupno" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v1-0}sRacuniUkupno"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sTijelo", propOrder = {
    "racuni",
    "ukupno"
})
public class STijelo {

    @XmlElement(name = "Racuni", required = true)
    protected SRacuniList racuni;
    @XmlElement(name = "Ukupno", required = true)
    protected SRacuniUkupno ukupno;

    /**
     * Gets the value of the racuni property.
     * 
     * @return
     *     possible object is
     *     {@link SRacuniList }
     *     
     */
    public SRacuniList getRacuni() {
        return racuni;
    }

    /**
     * Sets the value of the racuni property.
     * 
     * @param value
     *     allowed object is
     *     {@link SRacuniList }
     *     
     */
    public void setRacuni(SRacuniList value) {
        this.racuni = value;
    }

    /**
     * Gets the value of the ukupno property.
     * 
     * @return
     *     possible object is
     *     {@link SRacuniUkupno }
     *     
     */
    public SRacuniUkupno getUkupno() {
        return ukupno;
    }

    /**
     * Sets the value of the ukupno property.
     * 
     * @param value
     *     allowed object is
     *     {@link SRacuniUkupno }
     *     
     */
    public void setUkupno(SRacuniUkupno value) {
        this.ukupno = value;
    }

}
