//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.12 at 01:49:31 PM CET 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacura.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Zaglavlje obrasca
 * 
 * <p>Java class for sZaglavlje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sZaglavlje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Razdoblje" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v1-0}sRazdoblje"/>
 *         &lt;element name="Obveznik" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v1-0}sPorezniObveznik"/>
 *         &lt;element name="ObracunSastavio" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v1-0}sIspunjavatelj"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sZaglavlje", propOrder = {
    "razdoblje",
    "obveznik",
    "obracunSastavio"
})
public class SZaglavlje {

    @XmlElement(name = "Razdoblje", required = true)
    protected SRazdoblje razdoblje;
    @XmlElement(name = "Obveznik", required = true)
    protected SPorezniObveznik obveznik;
    @XmlElement(name = "ObracunSastavio", required = true)
    protected SIspunjavatelj obracunSastavio;

    /**
     * Gets the value of the razdoblje property.
     * 
     * @return
     *     possible object is
     *     {@link SRazdoblje }
     *     
     */
    public SRazdoblje getRazdoblje() {
        return razdoblje;
    }

    /**
     * Sets the value of the razdoblje property.
     * 
     * @param value
     *     allowed object is
     *     {@link SRazdoblje }
     *     
     */
    public void setRazdoblje(SRazdoblje value) {
        this.razdoblje = value;
    }

    /**
     * Gets the value of the obveznik property.
     * 
     * @return
     *     possible object is
     *     {@link SPorezniObveznik }
     *     
     */
    public SPorezniObveznik getObveznik() {
        return obveznik;
    }

    /**
     * Sets the value of the obveznik property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPorezniObveznik }
     *     
     */
    public void setObveznik(SPorezniObveznik value) {
        this.obveznik = value;
    }

    /**
     * Gets the value of the obracunSastavio property.
     * 
     * @return
     *     possible object is
     *     {@link SIspunjavatelj }
     *     
     */
    public SIspunjavatelj getObracunSastavio() {
        return obracunSastavio;
    }

    /**
     * Sets the value of the obracunSastavio property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIspunjavatelj }
     *     
     */
    public void setObracunSastavio(SIspunjavatelj value) {
        this.obracunSastavio = value;
    }

}
