//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.24 at 02:49:29 PM CEST 
//


package hr.sepa.pain_001_001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.sepa.pain_001_001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.03", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.sepa.pain_001_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification42 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification42 createBranchAndFinancialInstitutionIdentification42() {
        return new BranchAndFinancialInstitutionIdentification42();
    }

    /**
     * Create an instance of {@link BranchAndFinancialInstitutionIdentification41 }
     * 
     */
    public BranchAndFinancialInstitutionIdentification41 createBranchAndFinancialInstitutionIdentification41() {
        return new BranchAndFinancialInstitutionIdentification41();
    }

    /**
     * Create an instance of {@link CashAccount162 }
     * 
     */
    public CashAccount162 createCashAccount162() {
        return new CashAccount162();
    }

    /**
     * Create an instance of {@link AccountIdentification4Choice2 }
     * 
     */
    public AccountIdentification4Choice2 createAccountIdentification4Choice2() {
        return new AccountIdentification4Choice2();
    }

    /**
     * Create an instance of {@link CreditorReferenceType1Choice }
     * 
     */
    public CreditorReferenceType1Choice createCreditorReferenceType1Choice() {
        return new CreditorReferenceType1Choice();
    }

    /**
     * Create an instance of {@link GenericOrganisationIdentification1 }
     * 
     */
    public GenericOrganisationIdentification1 createGenericOrganisationIdentification1() {
        return new GenericOrganisationIdentification1();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification72 }
     * 
     */
    public FinancialInstitutionIdentification72 createFinancialInstitutionIdentification72() {
        return new FinancialInstitutionIdentification72();
    }

    /**
     * Create an instance of {@link FinancialInstitutionIdentification71 }
     * 
     */
    public FinancialInstitutionIdentification71 createFinancialInstitutionIdentification71() {
        return new FinancialInstitutionIdentification71();
    }

    /**
     * Create an instance of {@link AmountType3Choice }
     * 
     */
    public AmountType3Choice createAmountType3Choice() {
        return new AmountType3Choice();
    }

    /**
     * Create an instance of {@link ClearingSystemMemberIdentification2 }
     * 
     */
    public ClearingSystemMemberIdentification2 createClearingSystemMemberIdentification2() {
        return new ClearingSystemMemberIdentification2();
    }

    /**
     * Create an instance of {@link PaymentIdentification1 }
     * 
     */
    public PaymentIdentification1 createPaymentIdentification1() {
        return new PaymentIdentification1();
    }

    /**
     * Create an instance of {@link PersonIdentificationSchemeName1Choice }
     * 
     */
    public PersonIdentificationSchemeName1Choice createPersonIdentificationSchemeName1Choice() {
        return new PersonIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link PaymentInstructionInformation3 }
     * 
     */
    public PaymentInstructionInformation3 createPaymentInstructionInformation3() {
        return new PaymentInstructionInformation3();
    }

    /**
     * Create an instance of {@link StructuredRemittanceInformation7 }
     * 
     */
    public StructuredRemittanceInformation7 createStructuredRemittanceInformation7() {
        return new StructuredRemittanceInformation7();
    }

    /**
     * Create an instance of {@link ActiveOrHistoricCurrencyAndAmount }
     * 
     */
    public ActiveOrHistoricCurrencyAndAmount createActiveOrHistoricCurrencyAndAmount() {
        return new ActiveOrHistoricCurrencyAndAmount();
    }

    /**
     * Create an instance of {@link DateAndPlaceOfBirth }
     * 
     */
    public DateAndPlaceOfBirth createDateAndPlaceOfBirth() {
        return new DateAndPlaceOfBirth();
    }

    /**
     * Create an instance of {@link CashAccount16HR }
     * 
     */
    public CashAccount16HR createCashAccount16HR() {
        return new CashAccount16HR();
    }

    /**
     * Create an instance of {@link OrganisationIdentificationSchemeName1Choice }
     * 
     */
    public OrganisationIdentificationSchemeName1Choice createOrganisationIdentificationSchemeName1Choice() {
        return new OrganisationIdentificationSchemeName1Choice();
    }

    /**
     * Create an instance of {@link GenericPersonIdentification1 }
     * 
     */
    public GenericPersonIdentification1 createGenericPersonIdentification1() {
        return new GenericPersonIdentification1();
    }

    /**
     * Create an instance of {@link CategoryPurpose1Choice }
     * 
     */
    public CategoryPurpose1Choice createCategoryPurpose1Choice() {
        return new CategoryPurpose1Choice();
    }

    /**
     * Create an instance of {@link OrganisationIdentification4 }
     * 
     */
    public OrganisationIdentification4 createOrganisationIdentification4() {
        return new OrganisationIdentification4();
    }

    /**
     * Create an instance of {@link GenericAccountIdentification1 }
     * 
     */
    public GenericAccountIdentification1 createGenericAccountIdentification1() {
        return new GenericAccountIdentification1();
    }

    /**
     * Create an instance of {@link Purpose2Choice }
     * 
     */
    public Purpose2Choice createPurpose2Choice() {
        return new Purpose2Choice();
    }

    /**
     * Create an instance of {@link RemittanceInformation5 }
     * 
     */
    public RemittanceInformation5 createRemittanceInformation5() {
        return new RemittanceInformation5();
    }

    /**
     * Create an instance of {@link PartyIdentification321 }
     * 
     */
    public PartyIdentification321 createPartyIdentification321() {
        return new PartyIdentification321();
    }

    /**
     * Create an instance of {@link PartyIdentification322 }
     * 
     */
    public PartyIdentification322 createPartyIdentification322() {
        return new PartyIdentification322();
    }

    /**
     * Create an instance of {@link PostalAddress6 }
     * 
     */
    public PostalAddress6 createPostalAddress6() {
        return new PostalAddress6();
    }

    /**
     * Create an instance of {@link ServiceLevel8Choice }
     * 
     */
    public ServiceLevel8Choice createServiceLevel8Choice() {
        return new ServiceLevel8Choice();
    }

    /**
     * Create an instance of {@link AccountIdentification4ChoiceHR }
     * 
     */
    public AccountIdentification4ChoiceHR createAccountIdentification4ChoiceHR() {
        return new AccountIdentification4ChoiceHR();
    }

    /**
     * Create an instance of {@link CreditorReferenceType2 }
     * 
     */
    public CreditorReferenceType2 createCreditorReferenceType2() {
        return new CreditorReferenceType2();
    }

    /**
     * Create an instance of {@link LocalInstrument2Choice }
     * 
     */
    public LocalInstrument2Choice createLocalInstrument2Choice() {
        return new LocalInstrument2Choice();
    }

    /**
     * Create an instance of {@link Party6Choice }
     * 
     */
    public Party6Choice createParty6Choice() {
        return new Party6Choice();
    }

    /**
     * Create an instance of {@link GroupHeader32 }
     * 
     */
    public GroupHeader32 createGroupHeader32() {
        return new GroupHeader32();
    }

    /**
     * Create an instance of {@link CreditTransferTransactionInformation10 }
     * 
     */
    public CreditTransferTransactionInformation10 createCreditTransferTransactionInformation10() {
        return new CreditTransferTransactionInformation10();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation191 }
     * 
     */
    public PaymentTypeInformation191 createPaymentTypeInformation191() {
        return new PaymentTypeInformation191();
    }

    /**
     * Create an instance of {@link PaymentTypeInformation192 }
     * 
     */
    public PaymentTypeInformation192 createPaymentTypeInformation192() {
        return new PaymentTypeInformation192();
    }

    /**
     * Create an instance of {@link GenericFinancialIdentification1 }
     * 
     */
    public GenericFinancialIdentification1 createGenericFinancialIdentification1() {
        return new GenericFinancialIdentification1();
    }

    /**
     * Create an instance of {@link PersonIdentification5 }
     * 
     */
    public PersonIdentification5 createPersonIdentification5() {
        return new PersonIdentification5();
    }

    /**
     * Create an instance of {@link CreditorReferenceInformation2 }
     * 
     */
    public CreditorReferenceInformation2 createCreditorReferenceInformation2() {
        return new CreditorReferenceInformation2();
    }

    /**
     * Create an instance of {@link CustomerCreditTransferInitiationV03 }
     * 
     */
    public CustomerCreditTransferInitiationV03 createCustomerCreditTransferInitiationV03() {
        return new CustomerCreditTransferInitiationV03();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:scthr:pain.001.001.03", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
