//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.08 at 10:19:02 AM CEST 
//


package hr.fina.eracun.b2g.pki.getb2goutgoinginvoicestatus.v0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import hr.fina.eracun.b2g.invoicewebservicecomponents.v0.HeaderSupplierType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1}HeaderSupplier"/>
 *         &lt;element name="Data">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="B2GOutgoingInvoiceStatus">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="InvoiceYear" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "headerSupplier",
    "data"
})
@XmlRootElement(name = "GetB2GOutgoingInvoiceStatusMsg")
public class GetB2GOutgoingInvoiceStatusMsg {

    @XmlElement(name = "HeaderSupplier", namespace = "http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", required = true)
    protected HeaderSupplierType headerSupplier;
    @XmlElement(name = "Data", required = true)
    protected GetB2GOutgoingInvoiceStatusMsg.Data data;

    /**
     * Zaglavlje poruke
     * 
     * @return
     *     possible object is
     *     {@link HeaderSupplierType }
     *     
     */
    public HeaderSupplierType getHeaderSupplier() {
        return headerSupplier;
    }

    /**
     * Sets the value of the headerSupplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderSupplierType }
     *     
     */
    public void setHeaderSupplier(HeaderSupplierType value) {
        this.headerSupplier = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link GetB2GOutgoingInvoiceStatusMsg.Data }
     *     
     */
    public GetB2GOutgoingInvoiceStatusMsg.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetB2GOutgoingInvoiceStatusMsg.Data }
     *     
     */
    public void setData(GetB2GOutgoingInvoiceStatusMsg.Data value) {
        this.data = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="B2GOutgoingInvoiceStatus">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="InvoiceYear" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "b2GOutgoingInvoiceStatus"
    })
    public static class Data {

        @XmlElement(name = "B2GOutgoingInvoiceStatus", required = true)
        protected GetB2GOutgoingInvoiceStatusMsg.Data.B2GOutgoingInvoiceStatus b2GOutgoingInvoiceStatus;

        /**
         * Gets the value of the b2GOutgoingInvoiceStatus property.
         * 
         * @return
         *     possible object is
         *     {@link GetB2GOutgoingInvoiceStatusMsg.Data.B2GOutgoingInvoiceStatus }
         *     
         */
        public GetB2GOutgoingInvoiceStatusMsg.Data.B2GOutgoingInvoiceStatus getB2GOutgoingInvoiceStatus() {
            return b2GOutgoingInvoiceStatus;
        }

        /**
         * Sets the value of the b2GOutgoingInvoiceStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link GetB2GOutgoingInvoiceStatusMsg.Data.B2GOutgoingInvoiceStatus }
         *     
         */
        public void setB2GOutgoingInvoiceStatus(GetB2GOutgoingInvoiceStatusMsg.Data.B2GOutgoingInvoiceStatus value) {
            this.b2GOutgoingInvoiceStatus = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="SupplierInvoiceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="InvoiceYear" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "supplierInvoiceID",
            "invoiceYear"
        })
        public static class B2GOutgoingInvoiceStatus {

            @XmlElement(name = "SupplierInvoiceID", required = true)
            protected String supplierInvoiceID;
            @XmlElement(name = "InvoiceYear", required = true)
            protected BigInteger invoiceYear;

            /**
             * Gets the value of the supplierInvoiceID property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSupplierInvoiceID() {
                return supplierInvoiceID;
            }

            /**
             * Sets the value of the supplierInvoiceID property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSupplierInvoiceID(String value) {
                this.supplierInvoiceID = value;
            }

            /**
             * Gets the value of the invoiceYear property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getInvoiceYear() {
                return invoiceYear;
            }

            /**
             * Sets the value of the invoiceYear property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setInvoiceYear(BigInteger value) {
                this.invoiceYear = value;
            }

        }

    }

}
