//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 04:32:34 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPPO/v1-0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacppo.v1_0;
