//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 04:32:34 PM CEST 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacppo.v1_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Isporuke
 * 
 * <p>Java class for sIsporuke complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sIsporuke">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Isporuka" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPPO/v1-0}sIsporukaPodatak" maxOccurs="3" minOccurs="3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sIsporuke", propOrder = {
    "isporuka"
})
public class SIsporuke {

    @XmlElement(name = "Isporuka", required = true)
    protected List<SIsporukaPodatak> isporuka;

    /**
     * Gets the value of the isporuka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the isporuka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIsporuka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SIsporukaPodatak }
     * 
     * 
     */
    public List<SIsporukaPodatak> getIsporuka() {
        if (isporuka == null) {
            isporuka = new ArrayList<SIsporukaPodatak>();
        }
        return this.isporuka;
    }

}
