//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 04:32:34 PM CEST 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacppo.v1_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import hr.porezna_uprava.e_porezna.sheme.metapodaci.v2_0.SPPOmetapodaci;


/**
 * Struktura PPO obrasca
 * 
 * <p>Java class for sObrazacPPO complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sObrazacPPO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0}Metapodaci"/>
 *         &lt;element name="Zaglavlje" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPPO/v1-0}sZaglavlje"/>
 *         &lt;element name="Tijelo" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPPO/v1-0}sTijelo"/>
 *       &lt;/sequence>
 *       &lt;attribute name="verzijaSheme" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sObrazacPPO", propOrder = {
    "metapodaci",
    "zaglavlje",
    "tijelo"
})
public class SObrazacPPO {

    @XmlElement(name = "Metapodaci", namespace = "http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0", required = true)
    protected SPPOmetapodaci metapodaci;
    @XmlElement(name = "Zaglavlje", required = true)
    protected SZaglavlje zaglavlje;
    @XmlElement(name = "Tijelo", required = true)
    protected STijelo tijelo;
    @XmlAttribute(name = "verzijaSheme", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String verzijaSheme;

    /**
     * Gets the value of the metapodaci property.
     * 
     * @return
     *     possible object is
     *     {@link SPPOmetapodaci }
     *     
     */
    public SPPOmetapodaci getMetapodaci() {
        return metapodaci;
    }

    /**
     * Sets the value of the metapodaci property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPPOmetapodaci }
     *     
     */
    public void setMetapodaci(SPPOmetapodaci value) {
        this.metapodaci = value;
    }

    /**
     * Gets the value of the zaglavlje property.
     * 
     * @return
     *     possible object is
     *     {@link SZaglavlje }
     *     
     */
    public SZaglavlje getZaglavlje() {
        return zaglavlje;
    }

    /**
     * Sets the value of the zaglavlje property.
     * 
     * @param value
     *     allowed object is
     *     {@link SZaglavlje }
     *     
     */
    public void setZaglavlje(SZaglavlje value) {
        this.zaglavlje = value;
    }

    /**
     * Gets the value of the tijelo property.
     * 
     * @return
     *     possible object is
     *     {@link STijelo }
     *     
     */
    public STijelo getTijelo() {
        return tijelo;
    }

    /**
     * Sets the value of the tijelo property.
     * 
     * @param value
     *     allowed object is
     *     {@link STijelo }
     *     
     */
    public void setTijelo(STijelo value) {
        this.tijelo = value;
    }

    /**
     * Gets the value of the verzijaSheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerzijaSheme() {
        if (verzijaSheme == null) {
            return "1.0";
        } else {
            return verzijaSheme;
        }
    }

    /**
     * Sets the value of the verzijaSheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerzijaSheme(String value) {
        this.verzijaSheme = value;
    }

}
