//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.22 at 04:32:34 PM CEST 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacppo.v1_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tijelo obrasca
 * 
 * <p>Java class for sTijelo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sTijelo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Isporuke" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPPO/v1-0}sIsporuke"/>
 *         &lt;element name="Ukupno" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sTijelo", propOrder = {
    "isporuke",
    "ukupno"
})
public class STijelo {

    @XmlElement(name = "Isporuke", required = true)
    protected SIsporuke isporuke;
    @XmlElement(name = "Ukupno", required = true)
    protected BigDecimal ukupno;

    /**
     * Gets the value of the isporuke property.
     * 
     * @return
     *     possible object is
     *     {@link SIsporuke }
     *     
     */
    public SIsporuke getIsporuke() {
        return isporuke;
    }

    /**
     * Sets the value of the isporuke property.
     * 
     * @param value
     *     allowed object is
     *     {@link SIsporuke }
     *     
     */
    public void setIsporuke(SIsporuke value) {
        this.isporuke = value;
    }

    /**
     * Gets the value of the ukupno property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupno() {
        return ukupno;
    }

    /**
     * Sets the value of the ukupno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupno(BigDecimal value) {
        this.ukupno = value;
    }

}
