//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.20 at 02:12:40 AM CEST 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacppo20132014.v1_0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacppo20132014.v1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ObrazacPPO20132014_QNAME = new QName("http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPPO20132014/v1-0", "ObrazacPPO20132014");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacppo20132014.v1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SObrazacPPO20132014 }
     * 
     */
    public SObrazacPPO20132014 createSObrazacPPO20132014() {
        return new SObrazacPPO20132014();
    }

    /**
     * Create an instance of {@link SPodatak }
     * 
     */
    public SPodatak createSPodatak() {
        return new SPodatak();
    }

    /**
     * Create an instance of {@link SIsporuka }
     * 
     */
    public SIsporuka createSIsporuka() {
        return new SIsporuka();
    }

    /**
     * Create an instance of {@link SIsporuke }
     * 
     */
    public SIsporuke createSIsporuke() {
        return new SIsporuke();
    }

    /**
     * Create an instance of {@link SRazdoblje }
     * 
     */
    public SRazdoblje createSRazdoblje() {
        return new SRazdoblje();
    }

    /**
     * Create an instance of {@link SObracunSastavio }
     * 
     */
    public SObracunSastavio createSObracunSastavio() {
        return new SObracunSastavio();
    }

    /**
     * Create an instance of {@link SPoslovniSubjekt }
     * 
     */
    public SPoslovniSubjekt createSPoslovniSubjekt() {
        return new SPoslovniSubjekt();
    }

    /**
     * Create an instance of {@link SZaglavlje }
     * 
     */
    public SZaglavlje createSZaglavlje() {
        return new SZaglavlje();
    }

    /**
     * Create an instance of {@link SIsporukaPodatak }
     * 
     */
    public SIsporukaPodatak createSIsporukaPodatak() {
        return new SIsporukaPodatak();
    }

    /**
     * Create an instance of {@link SZastupnik }
     * 
     */
    public SZastupnik createSZastupnik() {
        return new SZastupnik();
    }

    /**
     * Create an instance of {@link STijelo }
     * 
     */
    public STijelo createSTijelo() {
        return new STijelo();
    }

    /**
     * Create an instance of {@link SPoslovniSubjektProsireno }
     * 
     */
    public SPoslovniSubjektProsireno createSPoslovniSubjektProsireno() {
        return new SPoslovniSubjektProsireno();
    }

    /**
     * Create an instance of {@link SPodaci }
     * 
     */
    public SPodaci createSPodaci() {
        return new SPodaci();
    }

    /**
     * Create an instance of {@link SAdresa }
     * 
     */
    public SAdresa createSAdresa() {
        return new SAdresa();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SObrazacPPO20132014 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPPO20132014/v1-0", name = "ObrazacPPO20132014")
    public JAXBElement<SObrazacPPO20132014> createObrazacPPO20132014(SObrazacPPO20132014 value) {
        return new JAXBElement<SObrazacPPO20132014>(_ObrazacPPO20132014_QNAME, SObrazacPPO20132014 .class, null, value);
    }

}
