//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.20 at 02:12:40 AM CEST 
//


package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacppo20132014.v1_0;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Isporuka
 * 
 * <p>Java class for sIsporukaPodatak complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sIsporukaPodatak">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Podaci" type="{http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPPO20132014/v1-0}sPodaci"/>
 *         &lt;element name="Iznos" type="{http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1}tDecimal15-2"/>
 *         &lt;element name="DatumOd" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DatumDo" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sIsporukaPodatak", propOrder = {
    "podaci",
    "iznos",
    "datumOd",
    "datumDo"
})
public class SIsporukaPodatak {

    @XmlElement(name = "Podaci", required = true)
    protected SPodaci podaci;
    @XmlElement(name = "Iznos", required = true)
    protected BigDecimal iznos;
    @XmlElement(name = "DatumOd", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumOd;
    @XmlElement(name = "DatumDo", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumDo;

    /**
     * Gets the value of the podaci property.
     * 
     * @return
     *     possible object is
     *     {@link SPodaci }
     *     
     */
    public SPodaci getPodaci() {
        return podaci;
    }

    /**
     * Sets the value of the podaci property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPodaci }
     *     
     */
    public void setPodaci(SPodaci value) {
        this.podaci = value;
    }

    /**
     * Gets the value of the iznos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIznos() {
        return iznos;
    }

    /**
     * Sets the value of the iznos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIznos(BigDecimal value) {
        this.iznos = value;
    }

    /**
     * Gets the value of the datumOd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumOd() {
        return datumOd;
    }

    /**
     * Sets the value of the datumOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumOd(XMLGregorianCalendar value) {
        this.datumOd = value;
    }

    /**
     * Gets the value of the datumDo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumDo() {
        return datumDo;
    }

    /**
     * Sets the value of the datumDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumDo(XMLGregorianCalendar value) {
        this.datumDo = value;
    }

}
