//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.16 at 11:30:49 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hr.porezna_uprava.e_porezna.sheme.zahtjevi.obrazacpdv.v9_0;
