//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.08 at 10:19:02 AM CEST 
//


package hr.fina.eracun.b2g.invoicewebservicecomponents.v0;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageAckType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageAckType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MessageAckID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MessageType" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="AckStatus" type="{http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1}AckStatusType"/>
 *         &lt;element name="AckStatusCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AckStatusText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageAckType", propOrder = {
    "messageID",
    "messageAckID",
    "messageType",
    "ackStatus",
    "ackStatusCode",
    "ackStatusText"
})
public class MessageAckType {

    @XmlElement(name = "MessageID", required = true)
    protected String messageID;
    @XmlElement(name = "MessageAckID", required = true)
    protected String messageAckID;
    @XmlElement(name = "MessageType", required = true)
    protected BigInteger messageType;
    @XmlElement(name = "AckStatus", required = true)
    @XmlSchemaType(name = "string")
    protected AckStatusType ackStatus;
    @XmlElement(name = "AckStatusCode")
    protected int ackStatusCode;
    @XmlElement(name = "AckStatusText")
    protected String ackStatusText;

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the messageAckID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageAckID() {
        return messageAckID;
    }

    /**
     * Sets the value of the messageAckID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageAckID(String value) {
        this.messageAckID = value;
    }

    /**
     * Gets the value of the messageType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMessageType() {
        return messageType;
    }

    /**
     * Sets the value of the messageType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMessageType(BigInteger value) {
        this.messageType = value;
    }

    /**
     * Gets the value of the ackStatus property.
     * 
     * @return
     *     possible object is
     *     {@link AckStatusType }
     *     
     */
    public AckStatusType getAckStatus() {
        return ackStatus;
    }

    /**
     * Sets the value of the ackStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link AckStatusType }
     *     
     */
    public void setAckStatus(AckStatusType value) {
        this.ackStatus = value;
    }

    /**
     * Gets the value of the ackStatusCode property.
     * 
     */
    public int getAckStatusCode() {
        return ackStatusCode;
    }

    /**
     * Sets the value of the ackStatusCode property.
     * 
     */
    public void setAckStatusCode(int value) {
        this.ackStatusCode = value;
    }

    /**
     * Gets the value of the ackStatusText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAckStatusText() {
        return ackStatusText;
    }

    /**
     * Sets the value of the ackStatusText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAckStatusText(String value) {
        this.ackStatusText = value;
    }

}
