//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.08 at 10:19:02 AM CEST 
//


package hr.fina.eracun.b2g.invoicewebservicecomponents.v0;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.fina.eracun.b2g.invoicewebservicecomponents.v0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HeaderSupplier_QNAME = new QName("http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", "HeaderSupplier");
    private final static QName _MessageAck_QNAME = new QName("http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", "MessageAck");
    private final static QName _Error_QNAME = new QName("http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", "Error");
    private final static QName _HeaderBuyer_QNAME = new QName("http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", "HeaderBuyer");
    private final static QName _DocumentStatus_QNAME = new QName("http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", "DocumentStatus");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.fina.eracun.b2g.invoicewebservicecomponents.v0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HeaderSupplierType }
     * 
     */
    public HeaderSupplierType createHeaderSupplierType() {
        return new HeaderSupplierType();
    }

    /**
     * Create an instance of {@link MessageAckType }
     * 
     */
    public MessageAckType createMessageAckType() {
        return new MessageAckType();
    }

    /**
     * Create an instance of {@link HeaderBuyerType }
     * 
     */
    public HeaderBuyerType createHeaderBuyerType() {
        return new HeaderBuyerType();
    }

    /**
     * Create an instance of {@link DocumentStatusType }
     * 
     */
    public DocumentStatusType createDocumentStatusType() {
        return new DocumentStatusType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HeaderSupplierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", name = "HeaderSupplier")
    public JAXBElement<HeaderSupplierType> createHeaderSupplier(HeaderSupplierType value) {
        return new JAXBElement<HeaderSupplierType>(_HeaderSupplier_QNAME, HeaderSupplierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageAckType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", name = "MessageAck")
    public JAXBElement<MessageAckType> createMessageAck(MessageAckType value) {
        return new JAXBElement<MessageAckType>(_MessageAck_QNAME, MessageAckType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", name = "Error")
    public JAXBElement<ErrorType> createError(ErrorType value) {
        return new JAXBElement<ErrorType>(_Error_QNAME, ErrorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HeaderBuyerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", name = "HeaderBuyer")
    public JAXBElement<HeaderBuyerType> createHeaderBuyer(HeaderBuyerType value) {
        return new JAXBElement<HeaderBuyerType>(_HeaderBuyer_QNAME, HeaderBuyerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentStatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fina.hr/eracun/b2g/invoicewebservicecomponents/v0.1", name = "DocumentStatus")
    public JAXBElement<DocumentStatusType> createDocumentStatus(DocumentStatusType value) {
        return new JAXBElement<DocumentStatusType>(_DocumentStatus_QNAME, DocumentStatusType.class, null, value);
    }

}
